"""
Tests for identify_lab() — Lab Identification
===============================================
Uses synthetic COA PDFs generated by conftest.py that contain
the URL and text fingerprints for each lab in the registry.
Analogous to scan_labs.py but deterministic and fully offline.
"""
import pytest

from cannlytics.data.coas.parser import identify_lab
from cannlytics.data.coas.registry import LAB_REGISTRY
from tests.conftest import LAB_PAGE_TEXTS


# ╔══════════════════════════════════════════════════════════════════╗
# ║ Lab Identification Tests                                         ║
# ╚══════════════════════════════════════════════════════════════════╝

class TestIdentifyLab:
    """Test identify_lab() against synthetic PDFs for every registered lab."""

    @pytest.mark.parametrize('lab_key', list(LAB_PAGE_TEXTS.keys()))
    def test_identifies_known_lab(self, lab_pdf_factory, lab_key):
        """Each lab's synthetic PDF should be correctly identified."""
        pdf_path = lab_pdf_factory(lab_key)
        identified = identify_lab(pdf_path)
        assert identified == lab_key, (
            f'Expected {lab_key}, got {identified} '
            f'for synthetic {lab_key} COA'
        )

    def test_unrecognized_returns_none(self, unrecognized_pdf):
        """A PDF without any lab fingerprints should return None."""
        identified = identify_lab(unrecognized_pdf)
        assert identified is None

    def test_nonexistent_file_returns_none(self):
        """A missing file should return None (not raise)."""
        identified = identify_lab('/nonexistent/coa.pdf')
        assert identified is None

    def test_url_match_takes_priority(self, make_pdf):
        """URL matching should have higher priority than text matching."""
        # Create a PDF with a Kaycha URL but SC Labs text.
        text = (
            'SC Labs\n'
            'yourcoa.com\n'
            'Certificate of Analysis'
        )
        pdf = make_pdf('mixed_signals.pdf', [text])
        # URL 'yourcoa.com' maps to Kaycha; text 'SC Labs' maps to sclabs.
        # URL match should win.
        identified = identify_lab(pdf)
        assert identified == 'kaycha'

    def test_deep_search_finds_page2(self, make_pdf):
        """With deep_search=True, lab fingerprints on page 2 should be found."""
        page1 = 'Certificate of Analysis\nGeneric Lab Report'
        page2 = 'Powered by Confident Cannabis\nconfidentcannabis.com'
        pdf = make_pdf('page2_lab.pdf', [page1, page2])
        identified = identify_lab(pdf, deep_search=True)
        assert identified == 'confidentcannabis'

    def test_deep_search_disabled(self, make_pdf):
        """With deep_search=False, fingerprints only on page 2 should not match."""
        page1 = 'Certificate of Analysis\nGeneric Lab Report'
        page2 = 'Powered by Confident Cannabis\nconfidentcannabis.com'
        pdf = make_pdf('page2_only.pdf', [page1, page2])
        identified = identify_lab(pdf, deep_search=False)
        assert identified is None

    def test_case_insensitive_text_match(self, make_pdf):
        """Text matching should be case-insensitive."""
        text = 'CERTIFICATE OF ANALYSIS\nKAYCHA LABS\nDate: 2024-01-01'
        pdf = make_pdf('uppercase.pdf', [text])
        identified = identify_lab(pdf)
        assert identified == 'kaycha'


# ╔══════════════════════════════════════════════════════════════════╗
# ║ Registry Coverage                                                ║
# ╚══════════════════════════════════════════════════════════════════╝

class TestRegistryCoverage:
    """Verify the test fixtures cover all labs in the registry."""

    def test_all_registry_labs_have_fixtures(self):
        """Every lab in LAB_REGISTRY should have a test fixture."""
        missing = set(LAB_REGISTRY.keys()) - set(LAB_PAGE_TEXTS.keys())
        assert missing == set(), (
            f'Labs in registry without test fixtures: {missing}. '
            f'Add entries to LAB_PAGE_TEXTS in conftest.py.'
        )

    def test_registry_entries_have_urls_and_patterns(self):
        """Every lab should have at least one URL or text pattern."""
        for lab_key, config in LAB_REGISTRY.items():
            urls = config.get('urls', [])
            patterns = config.get('text_patterns', [])
            assert urls or patterns, (
                f'Lab {lab_key} has no URLs or text patterns — '
                f'it can never be identified.'
            )
