#FROM node:14-alpine
FROM node:14-bullseye

WORKDIR /app

COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force

COPY . ./

EXPOSE 8080

CMD [ "npm", "run", "serve" ]

ENV PYTHONUNBUFFERED=1
RUN apt-get update && \
	apt-get install -yqq \
	python3 \
	python3-pip \
	python3-dev && \
	ln -sf python3 /usr/bin/python

RUN pip3 install --upgrade pip setuptools wheel

# ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
#RUN apt-get install -yqq \
#	gcc musl-dev libffi-dev postgresql-dev g++ jpeg-dev zlib-dev build-base
RUN pip3 install -r requirements.txt
RUN chown -R 1000:1000 "/root/.npm"
RUN npm install -D @webpack-cli/serve --force
