"""
Analyte Constants | Cannlytics
Copyright (c) 2021-2026 Cannlytics

Authors:
    Keegan Skeate <https://github.com/keeganskeate>
Created: 9/26/2026
Updated: 9/26/2026
License: MIT License <https://github.com/cannlytics/cannlytics/blob/main/LICENSE>

Description:
    The one home of the canonical analyte keys and the aliases that map
    a laboratory's own label onto them. Before 1.0.4 four tables lived
    in four repositories (the package, cannabis_results, and two in
    cannabis_analytes) and disagreed on Greek letters and on which of
    "2-propanol" and "isopropanol" was the key. The rules now:

    - Keys are ASCII snake_case: ``delta_9_thc``, ``beta_myrcene``.
    - Systematic names are canonical: ``2_propanol`` (``isopropanol``
      is an alias), ``pentachloronitrobenzene`` (``pcnb`` is an alias).
    - A specific compound beats an aggregate: ``aflatoxin_b1`` is not
      folded into ``total_aflatoxins``; ``n_hexane`` is not
      ``total_hexanes``.
    - Mycotoxins are their own analysis, not a kind of microbe.

    Use ``normalize_analyte_key`` to map any label to its key, and
    ``ANALYTE_TO_ANALYSIS`` to find the analysis a key belongs to.

        from cannlytics.constants import normalize_analyte_key
        normalize_analyte_key('Δ9-THC')    # 'delta_9_thc'
        normalize_analyte_key('Isopropanol')    # '2_propanol'

    Standard library only.
"""
# Standard imports:
import re
import unicodedata
from typing import Optional

# Greek letters and symbols that appear in laboratory labels, spelled
# out so that every key is ASCII.
_TRANSLITERATE = {
    'Δ': 'delta', 'δ': 'delta', 'α': 'alpha', 'β': 'beta', 'γ': 'gamma',
    'µ': 'u', 'μ': 'u', 'Σ': 'total', '∑': 'total', '°': '', '™': '', '®': '',
}

# ╔══════════════════════════════════════════════════════════════════╗
# ║ Canonical keys, by analysis                                      ║
# ╚══════════════════════════════════════════════════════════════════╝

CANNABINOIDS = [
    '9r_delta_10_thc', '9s_delta_10_thc', 'cbc', 'cbca', 'cbcv', 'cbd', 'cbda', 'cbdv',
    'cbdva', 'cbg', 'cbga', 'cbgv', 'cbgva', 'cbl', 'cbla', 'cbn', 'cbna', 'cbt', 'cbv',
    'cbva', 'delta_10_thc', 'delta_8_thc', 'delta_9_thc', 'delta_9_thc_per_serving',
    'exo_thc', 'thca', 'thcv', 'thcva', 'total_cannabinoids', 'total_cbd', 'total_thc',
    'total_thc_per_package',
]

TERPENES = [
    'alpha_bisabolene', 'alpha_bisabolol', 'alpha_bulnesene', 'alpha_cedrene',
    'alpha_farnesene', 'alpha_humulene', 'alpha_maaliene', 'alpha_ocimene',
    'alpha_phellandrene', 'alpha_pinene', 'alpha_terpinene', 'alpha_terpineol',
    'alpha_thujone', 'beta_caryophyllene', 'beta_eudesmol', 'beta_maaliene',
    'beta_myrcene', 'beta_ocimene', 'beta_pinene', 'borneol', 'camphene', 'camphor',
    'carvacrol', 'carvone', 'caryophyllene_oxide', 'cedrene', 'cedrol', 'cis_nerolidol',
    'cis_ocimene', 'citral', 'citronellol', 'cumene', 'd_isomenthone', 'd_limonene',
    'delta_3_carene', 'eucalyptol', 'fenchol', 'fenchone', 'gamma_terpinene',
    'gamma_terpineol', 'geraniol', 'geranyl_acetate', 'guaiol', 'isoborneol',
    'isobornyl_acetate', 'isopulegol', 'linalool', 'menthol', 'menthone', 'neral',
    'nerol', 'nerolidol', 'nootkatone', 'ocimene', 'octyl_acetate', 'p_cymene',
    'phytol', 'piperitone', 'pulegone', 'sabinene', 'sabinene_hydrate', 'safranal',
    'squalene', 'terpinen_4_ol', 'terpineol', 'terpinolene', 'thujone', 'thymol',
    'total_terpenes', 'trans_beta_farnesene', 'trans_nerolidol', 'trans_ocimene',
    'valencene', 'verbenone',
]

PESTICIDES = [
    'abamectin', 'acephate', 'acequinocyl', 'acetamiprid', 'aldicarb', 'allethrin',
    'ancymidol', 'atrazine', 'avermectin_b1a', 'avermectin_b1b', 'azadirachtin',
    'azoxystrobin', 'benzovindiflupyr', 'bifenazate', 'bifenthrin', 'boscalid',
    'buprofezin', 'captan', 'carbaryl', 'carbofuran', 'chlorantraniliprole',
    'chlordane', 'chlorfenapyr', 'chlormequat_chloride', 'chlorpyrifos',
    'cis_permethrin', 'clofentezine', 'clothianidin', 'coumaphos', 'cyantraniliprole',
    'cyfluthrin', 'cypermethrin', 'cyprodinil', 'daminozide', 'deltamethrin',
    'diazinon', 'dichlorvos', 'dimethoate', 'dimethomorph', 'dinotefuran', 'diuron',
    'dodemorph', 'endosulfan_sulfate', 'ethoprophos', 'etofenprox', 'etoxazole',
    'etridiazole', 'fenhexamid', 'fenoxycarb', 'fenpyroximate', 'fensulfothion',
    'fenthion', 'fenvalerate', 'fipronil', 'flonicamid', 'fludioxonil', 'fluopyram',
    'flurprimidol', 'hexythiazox', 'imazalil', 'imidacloprid', 'indole_3_butyric_acid',
    'iprodione', 'kresoxim_methyl', 'malathion', 'metalaxyl', 'methiocarb', 'methomyl',
    'methoprene', 'methyl_parathion', 'mevinphos', 'mgk_264', 'myclobutanil', 'naled',
    'novaluron', 'oxamyl', 'paclobutrazol', 'pentachloronitrobenzene', 'permethrin',
    'phenothrin', 'phosmet', 'piperonyl_butoxide', 'pirimicarb', 'prallethrin',
    'propiconazole', 'propoxur', 'pyraclostrobin', 'pyrethrin_i', 'pyrethrin_ii',
    'pyrethrins', 'pyridaben', 'pyriproxyfen', 'resmethrin', 'spinetoram', 'spinosad',
    'spinosad_a', 'spinosad_d', 'spirodiclofen', 'spiromesifen', 'spirotetramat',
    'spiroxamine', 'tebuconazole', 'tebufenozide', 'teflubenzuron', 'tetrachlorvinphos',
    'tetramethrin', 'thiabendazole', 'thiacloprid', 'thiamethoxam',
    'thiophanate_methyl', 'trans_permethrin', 'trifloxystrobin',
]

HEAVY_METALS = [
    'antimony', 'arsenic', 'cadmium', 'chromium', 'copper', 'lead', 'mercury', 'nickel',
    'selenium',
]

MICROBES = [
    'aspergillus', 'aspergillus_flavus', 'aspergillus_fumigatus', 'aspergillus_niger',
    'aspergillus_terreus', 'btgn', 'e_coli', 'enterobacteriaceae', 'listeria',
    'pseudomonas_aeruginosa', 'salmonella', 'staphylococcus_aureus', 'stec',
    'total_aerobic_bacteria', 'total_coliforms', 'total_yeast_and_mold',
]

MYCOTOXINS = [
    'aflatoxin_b1', 'aflatoxin_b2', 'aflatoxin_g1', 'aflatoxin_g2', 'ochratoxin_a',
    'total_aflatoxins',
]

RESIDUAL_SOLVENTS = [
    '1_2_dichloroethane', '1_2_dimethoxyethane', '2_2_dimethylbutane', '2_piperidone',
    '2_propanol', '3_methylpentane', 'acetone', 'acetonitrile', 'benzene', 'chloroform',
    'cyclohexane', 'dichloromethane', 'dimethyl_sulfoxide', 'ethanol', 'ethyl_acetate',
    'ethyl_ether', 'ethylene_oxide', 'isobutane', 'isopropyl_acetate', 'methanol',
    'n_butane', 'n_heptane', 'n_hexane', 'n_n_dimethyl_formamide', 'n_pentane',
    'propane', 'tetrafluoroethane', 'toluene', 'total_butanes', 'total_hexanes',
    'total_pentanes', 'total_xylenes', 'trichloroethane', 'trichloroethylene',
]

MOISTURE = [
    'moisture_content', 'water_activity',
]

FOREIGN_MATTER = [
    'foreign_matter', 'hair', 'insect_fragments', 'mammal_excrement', 'seeds', 'soil',
    'stems',
]

ANALYTE_KEYS = {
    'cannabinoids': CANNABINOIDS,
    'terpenes': TERPENES,
    'pesticides': PESTICIDES,
    'heavy_metals': HEAVY_METALS,
    'microbes': MICROBES,
    'mycotoxins': MYCOTOXINS,
    'residual_solvents': RESIDUAL_SOLVENTS,
    'moisture_content': MOISTURE,
    'foreign_matter': FOREIGN_MATTER,
}

# Every canonical key, sorted.
ALL_ANALYTE_KEYS = sorted(set().union(*ANALYTE_KEYS.values()))

# The analysis each canonical key belongs to.
ANALYTE_TO_ANALYSIS = {
    key: analysis for analysis, keys in ANALYTE_KEYS.items() for key in keys
}

# Isomers reported under one family name by some laboratories.
ANALYTE_FAMILIES = {
    'nerolidol': ['cis_nerolidol', 'trans_nerolidol'],
    'ocimene': ['cis_ocimene', 'trans_ocimene', 'beta_ocimene', 'cis_beta_ocimene', 'trans_beta_ocimene', 'alpha_ocimene'],
}

# ╔══════════════════════════════════════════════════════════════════╗
# ║ Display names                                                    ║
# ╚══════════════════════════════════════════════════════════════════╝

ANALYTE_NAMES = {
    '1_2_dichloroethane': '1-2 Dichloroethane',
    '1_2_dimethoxyethane': '1-2 Dimethoxyethane',
    '2_2_dimethylbutane': '2-2 Dimethylbutane',
    '2_piperidone': '2-Piperidone',
    '2_propanol': '2-Propanol',
    '3_methylpentane': '3-Methylpentane',
    '9r_delta_10_thc': '9R-Delta-10 THC',
    '9s_delta_10_thc': '9S-Delta-10 THC',
    'abamectin': 'Abamectin',
    'acephate': 'Acephate',
    'acequinocyl': 'Acequinocyl',
    'acetamiprid': 'Acetamiprid',
    'acetone': 'Acetone',
    'acetonitrile': 'Acetonitrile',
    'aflatoxin_b1': 'Aflatoxin B1',
    'aflatoxin_b2': 'Aflatoxin B2',
    'aflatoxin_g1': 'Aflatoxin G1',
    'aflatoxin_g2': 'Aflatoxin G2',
    'aldicarb': 'Aldicarb',
    'allethrin': 'Allethrin',
    'alpha_bisabolene': 'Alpha-Bisabolene',
    'alpha_bisabolol': 'Alpha-Bisabolol',
    'alpha_bulnesene': 'Alpha-Bulnesene',
    'alpha_cedrene': 'Alpha-Cedrene',
    'alpha_farnesene': 'Alpha-Farnesene',
    'alpha_humulene': 'Alpha-Humulene',
    'alpha_maaliene': 'Alpha-Maaliene',
    'alpha_ocimene': 'Alpha-Ocimene',
    'alpha_phellandrene': 'Alpha-Phellandrene',
    'alpha_pinene': 'Alpha-Pinene',
    'alpha_terpinene': 'Alpha-Terpinene',
    'alpha_terpineol': 'Alpha-Terpineol',
    'alpha_thujone': 'Alpha-Thujone',
    'ancymidol': 'Ancymidol',
    'antimony': 'Antimony',
    'arsenic': 'Arsenic',
    'aspergillus': 'Aspergillus',
    'aspergillus_flavus': 'Aspergillus Flavus',
    'aspergillus_fumigatus': 'Aspergillus Fumigatus',
    'aspergillus_niger': 'Aspergillus Niger',
    'aspergillus_terreus': 'Aspergillus Terreus',
    'atrazine': 'Atrazine',
    'avermectin_b1a': 'Avermectin B1a',
    'avermectin_b1b': 'Avermectin B1b',
    'azadirachtin': 'Azadirachtin',
    'azoxystrobin': 'Azoxystrobin',
    'benzene': 'Benzene',
    'benzovindiflupyr': 'Benzovindiflupyr',
    'beta_caryophyllene': 'Beta-Caryophyllene',
    'beta_eudesmol': 'Beta-Eudesmol',
    'beta_maaliene': 'Beta-Maaliene',
    'beta_myrcene': 'Beta-Myrcene',
    'beta_ocimene': 'Beta-Ocimene',
    'beta_pinene': 'Beta-Pinene',
    'bifenazate': 'Bifenazate',
    'bifenthrin': 'Bifenthrin',
    'borneol': 'Borneol',
    'boscalid': 'Boscalid',
    'btgn': 'BTGN',
    'buprofezin': 'Buprofezin',
    'cadmium': 'Cadmium',
    'camphene': 'Camphene',
    'camphor': 'Camphor',
    'captan': 'Captan',
    'carbaryl': 'Carbaryl',
    'carbofuran': 'Carbofuran',
    'carvacrol': 'Carvacrol',
    'carvone': 'Carvone',
    'caryophyllene_oxide': 'Caryophyllene Oxide',
    'cbc': 'CBC',
    'cbca': 'CBCA',
    'cbcv': 'CBCV',
    'cbd': 'CBD',
    'cbda': 'CBDA',
    'cbdv': 'CBDV',
    'cbdva': 'CBDVA',
    'cbg': 'CBG',
    'cbga': 'CBGA',
    'cbgv': 'CBGV',
    'cbgva': 'CBGVA',
    'cbl': 'CBL',
    'cbla': 'CBLA',
    'cbn': 'CBN',
    'cbna': 'CBNA',
    'cbt': 'CBT',
    'cbv': 'CBV',
    'cbva': 'CBVA',
    'cedrene': 'Cedrene',
    'cedrol': 'Cedrol',
    'chlorantraniliprole': 'Chlorantraniliprole',
    'chlordane': 'Chlordane',
    'chlorfenapyr': 'Chlorfenapyr',
    'chlormequat_chloride': 'Chlormequat Chloride',
    'chloroform': 'Chloroform',
    'chlorpyrifos': 'Chlorpyrifos',
    'chromium': 'Chromium',
    'cis_nerolidol': 'cis-Nerolidol',
    'cis_ocimene': 'cis-Ocimene',
    'cis_permethrin': 'cis-Permethrin',
    'citral': 'Citral',
    'citronellol': 'Citronellol',
    'clofentezine': 'Clofentezine',
    'clothianidin': 'Clothianidin',
    'copper': 'Copper',
    'coumaphos': 'Coumaphos',
    'cumene': 'Cumene',
    'cyantraniliprole': 'Cyantraniliprole',
    'cyclohexane': 'Cyclohexane',
    'cyfluthrin': 'Cyfluthrin',
    'cypermethrin': 'Cypermethrin',
    'cyprodinil': 'Cyprodinil',
    'd_isomenthone': 'D-Isomenthone',
    'd_limonene': 'D-Limonene',
    'daminozide': 'Daminozide',
    'delta_10_thc': 'Delta-10 THC',
    'delta_3_carene': 'Delta-3-Carene',
    'delta_8_thc': 'Delta-8 THC',
    'delta_9_thc': 'Delta-9 THC',
    'delta_9_thc_per_serving': 'Delta-9 THC per Serving',
    'deltamethrin': 'Deltamethrin',
    'diazinon': 'Diazinon',
    'dichloromethane': 'Dichloromethane',
    'dichlorvos': 'Dichlorvos',
    'dimethoate': 'Dimethoate',
    'dimethomorph': 'Dimethomorph',
    'dimethyl_sulfoxide': 'Dimethyl Sulfoxide',
    'dinotefuran': 'Dinotefuran',
    'diuron': 'Diuron',
    'dodemorph': 'Dodemorph',
    'e_coli': 'E. Coli',
    'endosulfan_sulfate': 'Endosulfan Sulfate',
    'enterobacteriaceae': 'Enterobacteriaceae',
    'ethanol': 'Ethanol',
    'ethoprophos': 'Ethoprophos',
    'ethyl_acetate': 'Ethyl Acetate',
    'ethyl_ether': 'Ethyl Ether',
    'ethylene_oxide': 'Ethylene Oxide',
    'etofenprox': 'Etofenprox',
    'etoxazole': 'Etoxazole',
    'etridiazole': 'Etridiazole',
    'eucalyptol': 'Eucalyptol',
    'exo_thc': 'exo-THC',
    'fenchol': 'Fenchol',
    'fenchone': 'Fenchone',
    'fenhexamid': 'Fenhexamid',
    'fenoxycarb': 'Fenoxycarb',
    'fenpyroximate': 'Fenpyroximate',
    'fensulfothion': 'Fensulfothion',
    'fenthion': 'Fenthion',
    'fenvalerate': 'Fenvalerate',
    'fipronil': 'Fipronil',
    'flonicamid': 'Flonicamid',
    'fludioxonil': 'Fludioxonil',
    'fluopyram': 'Fluopyram',
    'flurprimidol': 'Flurprimidol',
    'foreign_matter': 'Foreign Matter',
    'gamma_terpinene': 'Gamma-Terpinene',
    'gamma_terpineol': 'Gamma-Terpineol',
    'geraniol': 'Geraniol',
    'geranyl_acetate': 'Geranyl Acetate',
    'guaiol': 'Guaiol',
    'hair': 'Hair',
    'hexythiazox': 'Hexythiazox',
    'imazalil': 'Imazalil',
    'imidacloprid': 'Imidacloprid',
    'indole_3_butyric_acid': 'Indole 3 Butyric Acid',
    'insect_fragments': 'Insect Fragments',
    'iprodione': 'Iprodione',
    'isoborneol': 'Isoborneol',
    'isobornyl_acetate': 'Isobornyl Acetate',
    'isobutane': 'Isobutane',
    'isopropyl_acetate': 'Isopropyl Acetate',
    'isopulegol': 'Isopulegol',
    'kresoxim_methyl': 'Kresoxim Methyl',
    'lead': 'Lead',
    'linalool': 'Linalool',
    'listeria': 'Listeria',
    'malathion': 'Malathion',
    'mammal_excrement': 'Mammal Excrement',
    'menthol': 'Menthol',
    'menthone': 'Menthone',
    'mercury': 'Mercury',
    'metalaxyl': 'Metalaxyl',
    'methanol': 'Methanol',
    'methiocarb': 'Methiocarb',
    'methomyl': 'Methomyl',
    'methoprene': 'Methoprene',
    'methyl_parathion': 'Methyl Parathion',
    'mevinphos': 'Mevinphos',
    'mgk_264': 'Mgk 264',
    'moisture_content': 'Moisture Content',
    'myclobutanil': 'Myclobutanil',
    'n_butane': 'n-Butane',
    'n_heptane': 'n-Heptane',
    'n_hexane': 'n-Hexane',
    'n_n_dimethyl_formamide': 'n n-Dimethyl Formamide',
    'n_pentane': 'n-Pentane',
    'naled': 'Naled',
    'neral': 'Neral',
    'nerol': 'Nerol',
    'nerolidol': 'Nerolidol',
    'nickel': 'Nickel',
    'nootkatone': 'Nootkatone',
    'novaluron': 'Novaluron',
    'ochratoxin_a': 'Ochratoxin A',
    'ocimene': 'Ocimene',
    'octyl_acetate': 'Octyl Acetate',
    'oxamyl': 'Oxamyl',
    'p_cymene': 'p-Cymene',
    'paclobutrazol': 'Paclobutrazol',
    'pentachloronitrobenzene': 'Pentachloronitrobenzene',
    'permethrin': 'Permethrin',
    'phenothrin': 'Phenothrin',
    'phosmet': 'Phosmet',
    'phytol': 'Phytol',
    'piperitone': 'Piperitone',
    'piperonyl_butoxide': 'Piperonyl Butoxide',
    'pirimicarb': 'Pirimicarb',
    'prallethrin': 'Prallethrin',
    'propane': 'Propane',
    'propiconazole': 'Propiconazole',
    'propoxur': 'Propoxur',
    'pseudomonas_aeruginosa': 'Pseudomonas Aeruginosa',
    'pulegone': 'Pulegone',
    'pyraclostrobin': 'Pyraclostrobin',
    'pyrethrin_i': 'Pyrethrin I',
    'pyrethrin_ii': 'Pyrethrin II',
    'pyrethrins': 'Pyrethrins',
    'pyridaben': 'Pyridaben',
    'pyriproxyfen': 'Pyriproxyfen',
    'resmethrin': 'Resmethrin',
    'sabinene': 'Sabinene',
    'sabinene_hydrate': 'Sabinene Hydrate',
    'safranal': 'Safranal',
    'salmonella': 'Salmonella',
    'seeds': 'Seeds',
    'selenium': 'Selenium',
    'soil': 'Soil',
    'spinetoram': 'Spinetoram',
    'spinosad': 'Spinosad',
    'spinosad_a': 'Spinosad A',
    'spinosad_d': 'Spinosad D',
    'spirodiclofen': 'Spirodiclofen',
    'spiromesifen': 'Spiromesifen',
    'spirotetramat': 'Spirotetramat',
    'spiroxamine': 'Spiroxamine',
    'squalene': 'Squalene',
    'staphylococcus_aureus': 'Staphylococcus Aureus',
    'stec': 'STEC',
    'stems': 'Stems',
    'tebuconazole': 'Tebuconazole',
    'tebufenozide': 'Tebufenozide',
    'teflubenzuron': 'Teflubenzuron',
    'terpinen_4_ol': 'Terpinen-4-ol',
    'terpineol': 'Terpineol',
    'terpinolene': 'Terpinolene',
    'tetrachlorvinphos': 'Tetrachlorvinphos',
    'tetrafluoroethane': 'Tetrafluoroethane',
    'tetramethrin': 'Tetramethrin',
    'thca': 'THCA',
    'thcv': 'THCV',
    'thcva': 'THCVA',
    'thiabendazole': 'Thiabendazole',
    'thiacloprid': 'Thiacloprid',
    'thiamethoxam': 'Thiamethoxam',
    'thiophanate_methyl': 'Thiophanate Methyl',
    'thujone': 'Thujone',
    'thymol': 'Thymol',
    'toluene': 'Toluene',
    'total_aerobic_bacteria': 'Total Aerobic Bacteria',
    'total_aflatoxins': 'Total Aflatoxins',
    'total_butanes': 'Total Butanes',
    'total_cannabinoids': 'Total Cannabinoids',
    'total_cbd': 'Total CBD',
    'total_coliforms': 'Total Coliforms',
    'total_hexanes': 'Total Hexanes',
    'total_pentanes': 'Total Pentanes',
    'total_terpenes': 'Total Terpenes',
    'total_thc': 'Total THC',
    'total_thc_per_package': 'Total THC per Package',
    'total_xylenes': 'Total Xylenes',
    'total_yeast_and_mold': 'Total Yeast and Mold',
    'trans_beta_farnesene': 'trans-Beta-Farnesene',
    'trans_nerolidol': 'trans-Nerolidol',
    'trans_ocimene': 'trans-Ocimene',
    'trans_permethrin': 'trans-Permethrin',
    'trichloroethane': 'Trichloroethane',
    'trichloroethylene': 'Trichloroethylene',
    'trifloxystrobin': 'Trifloxystrobin',
    'valencene': 'Valencene',
    'verbenone': 'Verbenone',
    'water_activity': 'Water Activity',
}

# ╔══════════════════════════════════════════════════════════════════╗
# ║ Aliases: a laboratory's label, snake-cased, to the canonical key ║
# ╚══════════════════════════════════════════════════════════════════╝

# Look-ups go through `normalize_analyte_key`, which snake-cases the
# label the same way these keys were produced. Canonical keys map to
# themselves.
ANALYTE_ALIASES = {
    '0_1_guaiol': 'guaiol',
    '0_3_guaiol': 'guaiol',
    '1_2_dichloro_ethane': '1_2_dichloroethane',
    '1_2_dichloroethane': '1_2_dichloroethane',
    '1_2_dimethoxy_ethane': '1_2_dimethoxyethane',
    '1_2_dimethoxyethane': '1_2_dimethoxyethane',
    '1_8_cineole': 'eucalyptol',
    '1_r_camphor': 'camphor',
    '1_r_endo_fenchyl_alcohol': 'fenchol',
    '1_s_3_carene': 'delta_3_carene',
    '2_2_dimethyl_butane': '2_2_dimethylbutane',
    '2_2_dimethylbutane': '2_2_dimethylbutane',
    '2_piperidone': '2_piperidone',
    '2_propanol': '2_propanol',
    '2_propanol_ipa': '2_propanol',
    '2_propanol_isopropyl_alcohol': '2_propanol',
    '3_carene': 'delta_3_carene',
    '3_methyl_pentane': '3_methylpentane',
    '3_methylpentane': '3_methylpentane',
    '4_carene': 'delta_3_carene',
    '4_terpineol': 'terpinen_4_ol',
    '6_ar_9_r_delta_10_tetrahydrocannabinol_6_ar_9_r_delta_10_thc': '9r_delta_10_thc',
    '6_ar_9_s_delta_10_tetrahydrocannabinol_6_ar_9_s_delta_10_thc': '9s_delta_10_thc',
    '8_tetrahydrocannabinol_delta_8_thc': 'delta_8_thc',
    '8_thc': 'delta_8_thc',
    '9_thc': 'delta_9_thc',
    '9_thc_per_serving': 'delta_9_thc_per_serving',
    '9_thca': 'thca',
    '9r_d10_thc': '9r_delta_10_thc',
    '9r_delta10_thc': '9r_delta_10_thc',
    '9r_delta_10_thc': '9r_delta_10_thc',
    '9s_d10_thc': '9s_delta_10_thc',
    '9s_delta10_thc': '9s_delta_10_thc',
    '9s_delta_10_thc': '9s_delta_10_thc',
    'a_atoxin_b_1': 'aflatoxin_b1',
    'a_atoxin_g_1': 'aflatoxin_g1',
    'a_atoxin_g_2': 'aflatoxin_g2',
    'a_bisabolene': 'alpha_bisabolene',
    'a_bisabolol': 'alpha_bisabolol',
    'a_bulnesene': 'alpha_bulnesene',
    'a_cedrene': 'alpha_cedrene',
    'a_farnesene': 'alpha_farnesene',
    'a_flavus': 'aspergillus_flavus',
    'a_fumigatus': 'aspergillus_fumigatus',
    'a_humulene': 'alpha_humulene',
    'a_maaliene': 'alpha_maaliene',
    'a_niger': 'aspergillus_niger',
    'a_ocimene': 'alpha_ocimene',
    'a_phellandrene': 'alpha_phellandrene',
    'a_pinene': 'alpha_pinene',
    'a_terpinene': 'alpha_terpinene',
    'a_terpineol': 'alpha_terpineol',
    'a_terreus': 'aspergillus_terreus',
    'a_thujone': 'alpha_thujone',
    'a_w': 'water_activity',
    'abamectin': 'abamectin',
    'abamectin_b1a': 'avermectin_b1a',
    'abamectin_b1b': 'avermectin_b1b',
    'abamectin_b_1_a': 'avermectin_b1a',
    'abamectin_b_1_b': 'avermectin_b1b',
    'abamectin_ba': 'avermectin_b1a',
    'abamectin_bb': 'avermectin_b1b',
    'acephate': 'acephate',
    'acequinocyl': 'acequinocyl',
    'acetamidprid': 'acetamiprid',
    'acetamiprid': 'acetamiprid',
    'acetone': 'acetone',
    'acetonitrile': 'acetonitrile',
    'aerobic_plate_count': 'total_aerobic_bacteria',
    'afalatoxin_b_2': 'aflatoxin_b2',
    'aflatoxin_b1': 'aflatoxin_b1',
    'aflatoxin_b2': 'aflatoxin_b2',
    'aflatoxin_b_1': 'aflatoxin_b1',
    'aflatoxin_b_2': 'aflatoxin_b2',
    'aflatoxin_g1': 'aflatoxin_g1',
    'aflatoxin_g2': 'aflatoxin_g2',
    'aflatoxin_g_1': 'aflatoxin_g1',
    'aflatoxin_g_2': 'aflatoxin_g2',
    'aflatoxins': 'total_aflatoxins',
    'aiphaterpinea': 'alpha_terpineol',
    'aldicarb': 'aldicarb',
    'allethrin': 'allethrin',
    'aloha_humulene': 'alpha_humulene',
    'alpha_bisabolene': 'alpha_bisabolene',
    'alpha_bisabolol': 'alpha_bisabolol',
    'alpha_bisabolol_l': 'alpha_bisabolol',
    'alpha_bulnesene': 'alpha_bulnesene',
    'alpha_cedrene': 'alpha_cedrene',
    'alpha_farnesene': 'alpha_farnesene',
    'alpha_fenchyl_alcohol': 'fenchol',
    'alpha_humulene': 'alpha_humulene',
    'alpha_humutene': 'alpha_humulene',
    'alpha_maaliene': 'alpha_maaliene',
    'alpha_ocimene': 'alpha_ocimene',
    'alpha_phella': 'alpha_phellandrene',
    'alpha_phellandrane': 'alpha_phellandrene',
    'alpha_phellandrene': 'alpha_phellandrene',
    'alpha_pinane': 'alpha_pinene',
    'alpha_pinene': 'alpha_pinene',
    'alpha_terpinen': 'alpha_terpinene',
    'alpha_terpinene': 'alpha_terpinene',
    'alpha_terpineol': 'alpha_terpineol',
    'alpha_terpinolene': 'terpinolene',
    'alpha_thujone': 'alpha_thujone',
    'alphahumulene': 'alpha_humulene',
    'alphaterpinene': 'alpha_terpinene',
    'ancymidol': 'ancymidol',
    'antimony': 'antimony',
    'apc': 'total_aerobic_bacteria',
    'arsenic': 'arsenic',
    'arsenic_as': 'arsenic',
    'as': 'arsenic',
    'aspergillus': 'aspergillus',
    'aspergillus_detected_fail': 'aspergillus',
    'aspergillus_flavus': 'aspergillus_flavus',
    'aspergillus_flavus_not_present_in': 'aspergillus_flavus',
    'aspergillus_fumigatus': 'aspergillus_fumigatus',
    'aspergillus_fumigatus_not_present_in': 'aspergillus_fumigatus',
    'aspergillus_niger': 'aspergillus_niger',
    'aspergillus_niger_not_present_in': 'aspergillus_niger',
    'aspergillus_siger': 'aspergillus_niger',
    'aspergillus_spp': 'aspergillus',
    'aspergillus_terreus': 'aspergillus_terreus',
    'aspergillus_terreus_not_present_in': 'aspergillus_terreus',
    'aspirgillus': 'aspergillus',
    'atrazine': 'atrazine',
    'avermectin_b1a': 'avermectin_b1a',
    'avermectin_b1b': 'avermectin_b1b',
    'avermectin_b_1_a_abamectin': 'avermectin_b1b',
    'avermectin_b_1_b_abamectin': 'avermectin_b1b',
    'aw': 'water_activity',
    'azadirachtin': 'azadirachtin',
    'azoxystrobin': 'azoxystrobin',
    'b1': 'aflatoxin_b1',
    'b2': 'aflatoxin_b2',
    'b_caryophyllene': 'beta_caryophyllene',
    'b_eudesmol': 'beta_eudesmol',
    'b_farnesene': 'trans_beta_farnesene',
    'b_maaliene': 'beta_maaliene',
    'b_myrcene': 'beta_myrcene',
    'b_ocimene': 'beta_ocimene',
    'b_pinene': 'beta_pinene',
    'benzene': 'benzene',
    'benzovindiflupyr': 'benzovindiflupyr',
    'beta_caryophyllene': 'beta_caryophyllene',
    'beta_caryophyllene_oxide': 'caryophyllene_oxide',
    'beta_eudesmol': 'beta_eudesmol',
    'beta_farnesene': 'trans_beta_farnesene',
    'beta_maaliene': 'beta_maaliene',
    'beta_myrcene': 'beta_myrcene',
    'beta_ocimene': 'beta_ocimene',
    'beta_pinene': 'beta_pinene',
    'betacaryophyllene': 'beta_caryophyllene',
    'bifenazate': 'bifenazate',
    'bifentherin': 'bifenthrin',
    'bifenthrin': 'bifenthrin',
    'bile_tolerant_gram_neg_bacteria': 'enterobacteriaceae',
    'bile_tolerant_gram_negative_bacteria': 'btgn',
    'bisabolol': 'alpha_bisabolol',
    'borneol': 'borneol',
    'boscalid': 'boscalid',
    'btgn': 'btgn',
    'buprofezin': 'buprofezin',
    'butane': 'n_butane',
    'butanes': 'total_butanes',
    'butanes_total': 'total_butanes',
    'cadmium': 'cadmium',
    'cadmium_cd': 'cadmium',
    'camphene': 'camphene',
    'camphor': 'camphor',
    'camphors': 'camphor',
    'cannabichromene': 'cbc',
    'cannabichromene_cbc': 'cbc',
    'cannabichromenic_acid': 'cbca',
    'cannabichromenic_acid_cbca': 'cbca',
    'cannabichromevarin': 'cbcv',
    'cannabicitran': 'cbt',
    'cannabicyclol': 'cbl',
    'cannabicyclol_cbl': 'cbl',
    'cannabicyclolic_acid': 'cbla',
    'cannabidiol': 'cbd',
    'cannabidiol_cbd': 'cbd',
    'cannabidiolic_acid': 'cbda',
    'cannabidiolic_acid_cbda': 'cbda',
    'cannabidivaric_acid': 'cbdva',
    'cannabidivarin': 'cbdv',
    'cannabidivarin_cbdv': 'cbdv',
    'cannabidivarinic_acid': 'cbdva',
    'cannabidivarinic_acid_cbdva': 'cbdva',
    'cannabigerol': 'cbg',
    'cannabigerol_cbg': 'cbg',
    'cannabigerolic_acid': 'cbga',
    'cannabigerolic_acid_cbga': 'cbga',
    'cannabigerovarin': 'cbgv',
    'cannabigerovarinic_acid': 'cbgva',
    'cannabigerovarinic_acid_a': 'cbgva',
    'cannabinadiolic_acid_cbda': 'cbda',
    'cannabinoids_total': 'total_cannabinoids',
    'cannabinol': 'cbn',
    'cannabinol_cbn': 'cbn',
    'cannabinolic_acid': 'cbna',
    'cannabivarin': 'cbv',
    'cannabivarinic_acid': 'cbva',
    'captan': 'captan',
    'carbaryl': 'carbaryl',
    'carbofuran': 'carbofuran',
    'carbotfuran': 'carbofuran',
    'carene': 'delta_3_carene',
    'carophyllene_oxide': 'caryophyllene_oxide',
    'carvacrol': 'carvacrol',
    'carvone': 'carvone',
    'caryophyliene_oxide': 'caryophyllene_oxide',
    'caryophyllene': 'beta_caryophyllene',
    'caryophyllene_oxide': 'caryophyllene_oxide',
    'caryophylleneoxide': 'caryophyllene_oxide',
    'cbc': 'cbc',
    'cbc_a': 'cbca',
    'cbca': 'cbca',
    'cbca_3': 'cbca',
    'cbcv': 'cbcv',
    'cbd': 'cbd',
    'cbd_a': 'cbda',
    'cbd_v': 'cbdv',
    'cbd_va': 'cbdva',
    'cbda': 'cbda',
    'cbdv': 'cbdv',
    'cbdv_a': 'cbdva',
    'cbdva': 'cbdva',
    'cbg': 'cbg',
    'cbg_a': 'cbga',
    'cbg_v': 'cbgv',
    'cbg_va': 'cbgva',
    'cbga': 'cbga',
    'cbgv': 'cbgv',
    'cbgva': 'cbgva',
    'cbl': 'cbl',
    'cbl_3': 'cbl',
    'cbl_a': 'cbla',
    'cbla': 'cbla',
    'cbn': 'cbn',
    'cbn_a': 'cbna',
    'cbna': 'cbna',
    'cbna_3': 'cbna',
    'cbt': 'cbt',
    'cbtc': 'cbt',
    'cbv': 'cbv',
    'cbva': 'cbva',
    'cc': 'total_coliforms',
    'cd': 'cadmium',
    'cedrene': 'cedrene',
    'cedrol': 'cedrol',
    'chlorantranil_iprole': 'chlorantraniliprole',
    'chlorantranilip_role': 'chlorantraniliprole',
    'chlorantraniliprole': 'chlorantraniliprole',
    'chlorantranilprole': 'chlorantraniliprole',
    'chlordane': 'chlordane',
    'chlordane_cis': 'chlordane',
    'chlordane_trans': 'chlordane',
    'chlorfenapyr': 'chlorfenapyr',
    'chlormequat_chloride': 'chlormequat_chloride',
    'chloroform': 'chloroform',
    'chlorpyrifos': 'chlorpyrifos',
    'chromium': 'chromium',
    'cineole': 'eucalyptol',
    'cis_beta_ocimene': 'beta_ocimene',
    'cis_geraniol': 'geraniol',
    'cis_nerolidol': 'cis_nerolidol',
    'cis_ocimene': 'cis_ocimene',
    'cis_permethrin': 'cis_permethrin',
    'citral': 'citral',
    'citronellol': 'citronellol',
    'clofentezine': 'clofentezine',
    'clofentizine': 'clofentezine',
    'clothianadin': 'clothianidin',
    'clothianidin': 'clothianidin',
    'coliforms': 'total_coliforms',
    'copper': 'copper',
    'coumaphos': 'coumaphos',
    'cr': 'chromium',
    'cu': 'copper',
    'cumene': 'cumene',
    'cy_uthrin': 'cyfluthrin',
    'cyantraniliprole': 'cyantraniliprole',
    'cyclohexane': 'cyclohexane',
    'cyfluthrin': 'cyfluthrin',
    'cyfluthrin_i': 'cyfluthrin',
    'cyfluthrin_ii': 'cyfluthrin',
    'cyfluthrin_iii': 'cyfluthrin',
    'cyfluthrin_iv': 'cyfluthrin',
    'cypermethrin': 'cypermethrin',
    'cypermethrin_i': 'cypermethrin',
    'cypermethrin_ii': 'cypermethrin',
    'cypermethrin_iii': 'cypermethrin',
    'cypermethrin_iv': 'cypermethrin',
    'cyprodinil': 'cyprodinil',
    'd10_thc': '9r_delta_10_thc',
    'd10thc': '9r_delta_10_thc',
    'd8_tetrahydrocannabinol': 'delta_8_thc',
    'd8_thc': 'delta_8_thc',
    'd8thc': 'delta_8_thc',
    'd9_tetrahydrocannabinol': 'delta_9_thc',
    'd9_thc': 'delta_9_thc',
    'd9thc': 'delta_9_thc',
    'd_10_tetrahydrocannabinoid_d_10_thc': 'delta_10_thc',
    'd_10_thc': 'delta_10_thc',
    'd_3_carene': 'delta_3_carene',
    'd_8_tetrahydrocannabinoid_d_8_thc': 'delta_8_thc',
    'd_8_thc': 'delta_8_thc',
    'd_9_othc': 'delta_9_thc',
    'd_9_tetrahydrocannabinoid_d_9_thc': 'delta_9_thc',
    'd_9_tetrahydrocannabinolic_acid_thca': 'thca',
    'd_9_thc': 'delta_9_thc',
    'd_9_thc_per_serving': 'delta_9_thc_per_serving',
    'd_9_thca': 'thca',
    'd_9_thcv': 'thcv',
    'd_9_thcva': 'thcva',
    'd_isomenthone': 'd_isomenthone',
    'd_limonene': 'd_limonene',
    'd_valerolactam_2_piperidone': '2_piperidone',
    'daminozide': 'daminozide',
    'ddvp': 'dichlorvos',
    'ddvp_dichlorvos': 'dichlorvos',
    'ddvp_dichlorvous': 'dichlorvos',
    'delta10thc': '9r_delta_10_thc',
    'delta3_carene': 'delta_3_carene',
    'delta8': 'delta_8_thc',
    'delta8thc': 'delta_8_thc',
    'delta9': 'delta_9_thc',
    'delta9_thc': 'delta_9_thc',
    'delta9thc': 'delta_9_thc',
    'delta_10_tetrahydrocannabinol': '9r_delta_10_thc',
    'delta_10_thc': 'delta_10_thc',
    'delta_3_carene': 'delta_3_carene',
    'delta_8_tetrahydrocannabinol': 'delta_8_thc',
    'delta_8_thc': 'delta_8_thc',
    'delta_8_thc_d_8_thc': 'delta_8_thc',
    'delta_9_tetrahydrocannabinol': 'delta_9_thc',
    'delta_9_tetrahydrocannabinol_delta_9_thc': 'delta_9_thc',
    'delta_9_thc': 'delta_9_thc',
    'delta_9_thc_d_9_thc': 'delta_9_thc',
    'delta_9_thc_per_packagepackage_3_5_grams': 'total_thc_per_package',
    'delta_9_thc_per_serving': 'delta_9_thc_per_serving',
    'delta_9_thca': 'thca',
    'delta_limonene': 'd_limonene',
    'deltamethrin': 'deltamethrin',
    'deltamethrine': 'deltamethrin',
    'diazanon': 'diazinon',
    'diazinon': 'diazinon',
    'dichloromethane': 'dichloromethane',
    'dichloromethane_methylene_chloride': 'dichloromethane',
    'dichlorvos': 'dichlorvos',
    'dichlorvos_ddvp': 'dichlorvos',
    'dimethoate': 'dimethoate',
    'dimethomorph': 'dimethomorph',
    'dimethomorph_e': 'dimethomorph',
    'dimethomorph_i': 'dimethomorph',
    'dimethomorph_ii': 'dimethomorph',
    'dimethomorph_z': 'dimethomorph',
    'dimethyl_sulfoxide': 'dimethyl_sulfoxide',
    'dinotefuran': 'dinotefuran',
    'diuron': 'diuron',
    'dl_menthol': 'menthol',
    'dodemorph': 'dodemorph',
    'e_beta_farnesene': 'trans_beta_farnesene',
    'e_caryophyllene': 'beta_caryophyllene',
    'e_coli': 'e_coli',
    'e_coli_detected_fail': 'e_coli',
    'e_coli_stec': 'stec',
    'e_nerolidol': 'nerolidol',
    'ecoli_shigella': 'e_coli',
    'endo_fenchyl': 'fenchol',
    'endo_fenchyl_alcohol': 'fenchol',
    'endosulfan_sulfate': 'endosulfan_sulfate',
    'enterobacteriaceae': 'enterobacteriaceae',
    'escherichia_coli': 'e_coli',
    'escherichia_coli_shigella': 'e_coli',
    'escherichia_coli_shigella_spp': 'e_coli',
    'escherichia_coli_shigella_spp_not_present_in': 'e_coli',
    'escherichia_coli_specific': 'e_coli',
    'escherichia_coli_stec': 'e_coli',
    'ethanol': 'ethanol',
    'ethoprop_hos': 'ethoprophos',
    'ethoprophos': 'ethoprophos',
    'ethyl_acetate': 'ethyl_acetate',
    'ethyl_ether': 'ethyl_ether',
    'ethylene_oxide': 'ethylene_oxide',
    'eto': 'ethylene_oxide',
    'etofenprox': 'etofenprox',
    'etoxazole': 'etoxazole',
    'etridiazole': 'etridiazole',
    'eucalyptol': 'eucalyptol',
    'exo_tetrahydrocannabinol_exo_thc': 'exo_thc',
    'exo_thc': 'exo_thc',
    'farnesene': 'trans_beta_farnesene',
    'fenchol': 'fenchol',
    'fenchone': 'fenchone',
    'fenchyl_alcohol': 'fenchol',
    'fenhexamid': 'fenhexamid',
    'fenhexamide': 'fenhexamid',
    'fenoxycarb': 'fenoxycarb',
    'fenpryoximate': 'fenpyroximate',
    'fenpyroximate': 'fenpyroximate',
    'fensulfothion': 'fensulfothion',
    'fenthion': 'fenthion',
    'fenvalerate': 'fenvalerate',
    'filth_and_foreign_matter': 'foreign_matter',
    'filth_foreign_matter': 'foreign_matter',
    'fipronil': 'fipronil',
    'flonicamid': 'flonicamid',
    'fludioxanil': 'fludioxonil',
    'fludioxonil': 'fludioxonil',
    'fluopyram': 'fluopyram',
    'flurprimidol': 'flurprimidol',
    'foreign_material': 'foreign_matter',
    'foreign_materials': 'foreign_matter',
    'foreign_matter': 'foreign_matter',
    'foreign_matter_i_h_e': 'foreign_matter',
    'foreign_matter_inspection': 'foreign_matter',
    'foreign_matter_stems': 'stems',
    'g1': 'aflatoxin_g1',
    'g2': 'aflatoxin_g2',
    'g_terpinene': 'gamma_terpinene',
    'g_terpineol': 'gamma_terpineol',
    'gama_terpinene': 'gamma_terpinene',
    'gamma_terpinene': 'gamma_terpinene',
    'gamma_terpineol': 'gamma_terpineol',
    'gammaterpinene': 'gamma_terpinene',
    'gammaterpineol': 'gamma_terpineol',
    'gammaz_terpinene': 'gamma_terpinene',
    'geraniol': 'geraniol',
    'geranyl': 'geranyl_acetate',
    'geranyl_acetate': 'geranyl_acetate',
    'geranylacetate': 'geranyl_acetate',
    'guaiol': 'guaiol',
    'hair': 'hair',
    'hair_count': 'hair',
    'heptane': 'n_heptane',
    'heptanes': 'n_heptane',
    'hexahydro_thymol': 'menthol',
    'hexahydrothymol': 'menthol',
    'hexane': 'n_hexane',
    'hexanes': 'total_hexanes',
    'hexanes_total': 'total_hexanes',
    'hexythiazox': 'hexythiazox',
    'hg': 'mercury',
    'humulene': 'alpha_humulene',
    'if_rh_me': 'foreign_matter',
    'ifm': 'foreign_matter',
    'imazalil': 'imazalil',
    'imazlil': 'imazalil',
    'imbedded_foreign_material': 'foreign_matter',
    'imidacloprid': 'imidacloprid',
    'indole_3_butyric_acid': 'indole_3_butyric_acid',
    'insect_fragment': 'insect_fragments',
    'insect_fragment_count': 'insect_fragments',
    'insect_fragments': 'insect_fragments',
    'insect_fragments_hair_mammal_excrement': 'foreign_matter',
    'insects': 'insect_fragments',
    'ipa': '2_propanol',
    'iprodione': 'iprodione',
    'iso_butane': 'isobutane',
    'isoborneol': 'isoborneol',
    'isobornyl_acetate': 'isobornyl_acetate',
    'isobutane': 'isobutane',
    'isomenthone': 'd_isomenthone',
    'isopropanol': '2_propanol',
    'isopropyl_acetate': 'isopropyl_acetate',
    'isopropyl_alcohol': '2_propanol',
    'isopropylacetate': 'isopropyl_acetate',
    'isopropylalcohol': '2_propanol',
    'isopulegol': 'isopulegol',
    'kresoxim_methyl': 'kresoxim_methyl',
    'kresoxin_methyl': 'kresoxim_methyl',
    'l_fenchone': 'fenchone',
    'l_menthol': 'menthol',
    'lead': 'lead',
    'lead_pb': 'lead',
    'limonene': 'd_limonene',
    'linalool': 'linalool',
    'listeria': 'listeria',
    'listeria_monocytogenes': 'listeria',
    'loq_endo_fenchyl_alcohol': 'fenchol',
    'loq_isoborneol': 'isoborneol',
    'loq_terpineol': 'terpineol',
    'lsobomneol': 'isoborneol',
    'lsoborneol': 'isoborneol',
    'lsopropyl_alcohol': '2_propanol',
    'lsopulegol': 'isopulegol',
    'm_p_xylene': 'total_xylenes',
    'malathion': 'malathion',
    'mammal_excrement': 'mammal_excrement',
    'mammalian_excreta': 'mammal_excrement',
    'mammalian_excreta_count': 'foreign_matter',
    'menthol': 'menthol',
    'menthol_hexahydrothymol': 'menthol',
    'menthone': 'menthone',
    'mercury': 'mercury',
    'mercury_hg': 'mercury',
    'metalaxyl': 'metalaxyl',
    'methanol': 'methanol',
    'methiocarb': 'methiocarb',
    'methomy': 'methomyl',
    'methomyl': 'methomyl',
    'methoprene': 'methoprene',
    'methyl_parathion': 'methyl_parathion',
    'methylene_chloride': 'dichloromethane',
    'mevinphos': 'mevinphos',
    'mevinphos_i': 'mevinphos',
    'mevinphos_ii': 'mevinphos',
    'mgk264': 'mgk_264',
    'mgk_264': 'mgk_264',
    'mgk_264_i_ii': 'mgk_264',
    'moisture': 'moisture_content',
    'moisture_content': 'moisture_content',
    'mold': 'total_yeast_and_mold',
    'myclobutanil': 'myclobutanil',
    'myrcene': 'beta_myrcene',
    'n_butane': 'n_butane',
    'n_heptane': 'n_heptane',
    'n_hexane': 'n_hexane',
    'n_n_dimethyl_formamide': 'n_n_dimethyl_formamide',
    'n_n_dimethylformamide': 'n_n_dimethyl_formamide',
    'n_pentane': 'n_pentane',
    'naled': 'naled',
    'neral': 'neral',
    'nerol': 'nerol',
    'nerolidol': 'nerolidol',
    'ni': 'nickel',
    'nickel': 'nickel',
    'nootkatone': 'nootkatone',
    'novaluron': 'novaluron',
    'ochratoxin': 'ochratoxin_a',
    'ochratoxin_a': 'ochratoxin_a',
    'ocimene': 'ocimene',
    'ocimene_isomer_i': 'alpha_ocimene',
    'ocimene_isomer_ii': 'beta_ocimene',
    'octyl_acetate': 'octyl_acetate',
    'octylacetate': 'octyl_acetate',
    'oxamyl': 'oxamyl',
    'p_aeruginosa': 'pseudomonas_aeruginosa',
    'p_and_m_xylene': 'total_xylenes',
    'p_cymene': 'p_cymene',
    'p_isopropyltoluene': 'p_cymene',
    'p_mentha_15_diene': 'alpha_phellandrene',
    'p_mentha_1_5_diene': 'alpha_phellandrene',
    'paclobutrazol': 'paclobutrazol',
    'para_cymene': 'p_cymene',
    'parathion_methyl': 'methyl_parathion',
    'pathogenic_aspergillus_spp': 'aspergillus',
    'pathogenic_e_coli': 'stec',
    'pb': 'lead',
    'pcnb': 'pentachloronitrobenzene',
    'pentachloroni_trobenzene': 'pentachloronitrobenzene',
    'pentachloronitro_benzene': 'pentachloronitrobenzene',
    'pentachloronitrobenzene': 'pentachloronitrobenzene',
    'pentachloronitrobenzene_pcnb': 'pentachloronitrobenzene',
    'pentane': 'n_pentane',
    'pentanes': 'total_pentanes',
    'pentanes_n_pentane': 'n_pentane',
    'pentanes_total': 'total_pentanes',
    'permethrin': 'permethrin',
    'permethrin_cis': 'cis_permethrin',
    'permethrin_trans': 'trans_permethrin',
    'permethrins': 'permethrin',
    'permethrins_total': 'permethrin',
    'phenothrin': 'phenothrin',
    'phosemet': 'phosmet',
    'phosmet': 'phosmet',
    'phytol': 'phytol',
    'piperitone': 'piperitone',
    'piperonyl_butoxide': 'piperonyl_butoxide',
    'piperonyl_butoxide_pbo': 'piperonyl_butoxide',
    'piperonylbu_toxide': 'piperonyl_butoxide',
    'piperonylbuto_xide': 'piperonyl_butoxide',
    'pirimicarb': 'pirimicarb',
    'prallethrin': 'prallethrin',
    'propan_2_ol': '2_propanol',
    'propane': 'propane',
    'propiconazole': 'propiconazole',
    'propoxur': 'propoxur',
    'pseudomonas': 'pseudomonas_aeruginosa',
    'pseudomonas_aeruginosa': 'pseudomonas_aeruginosa',
    'pulegone': 'pulegone',
    'pyraclostrobin': 'pyraclostrobin',
    'pyrethrin': 'pyrethrins',
    'pyrethrin_i': 'pyrethrin_i',
    'pyrethrin_ii': 'pyrethrin_ii',
    'pyrethrins': 'pyrethrins',
    'pyrethrins_pyrethrin_i': 'pyrethrins',
    'pyrethrins_pyrethrin_ii': 'pyrethrins',
    'pyrethrins_total': 'pyrethrins',
    'pyridaben': 'pyridaben',
    'pyriproxifen': 'pyriproxyfen',
    'pyriproxyfen': 'pyriproxyfen',
    'quintozene': 'pentachloronitrobenzene',
    'r_carvone': 'carvone',
    'r_delta_10_thc': '9r_delta_10_thc',
    'r_endo_fenchyl_alcohol': 'fenchol',
    'r_limonene': 'd_limonene',
    'r_pulegone': 'pulegone',
    'resmethrin': 'resmethrin',
    's_aureus': 'staphylococcus_aureus',
    's_carvone': 'carvone',
    's_delta_10_thc': '9s_delta_10_thc',
    'sabinene': 'sabinene',
    'sabinene_hydrate': 'sabinene_hydrate',
    'sabinenehydrate': 'sabinene_hydrate',
    'safranal': 'safranal',
    'salmonella': 'salmonella',
    'salmonella_aoac': 'salmonella',
    'salmonella_detected_fail': 'salmonella',
    'salmonella_species': 'salmonella',
    'salmonella_specific_gene': 'salmonella',
    'salmonella_specific_gene_not_present_in': 'salmonella',
    'salmonella_spp': 'salmonella',
    'sand': 'soil',
    'sand_soil_cinders_dirt': 'soil',
    'sand_soils_cinders_and_dirt': 'soil',
    'sb': 'antimony',
    'se': 'selenium',
    'seeds': 'seeds',
    'selenium': 'selenium',
    'shiga_toxin_e_coli': 'stec',
    'shiga_toxin_producing_e_coli': 'stec',
    'shiga_toxin_producing_escherichia_coli': 'e_coli',
    'soil': 'soil',
    'spinetoram': 'spinetoram',
    'spinetoram_j': 'spinetoram',
    'spinetoram_l': 'spinetoram',
    'spinetoram_total': 'spinetoram',
    'spinosad': 'spinosad',
    'spinosad_a': 'spinosad_a',
    'spinosad_d': 'spinosad_d',
    'spinosad_total': 'spinosad',
    'spinosyn_a': 'spinosad_a',
    'spinosyn_a_spinosad': 'spinosad_a',
    'spinosyn_d': 'spinosad_d',
    'spinosyn_d_spinosad': 'spinosad_d',
    'spirodiclofen': 'spirodiclofen',
    'spiromesifen': 'spiromesifen',
    'spirotetramat': 'spirotetramat',
    'spiroxamine': 'spiroxamine',
    'squalene': 'squalene',
    'sscd': 'soil',
    'staph_aureus': 'staphylococcus_aureus',
    'staphylococcus_aureus': 'staphylococcus_aureus',
    'stec': 'stec',
    'stec_e_coli': 'stec',
    'stems': 'stems',
    'tac': 'total_aerobic_bacteria',
    'tamc': 'total_aerobic_bacteria',
    'tce': 'trichloroethylene',
    'tcvp': 'tetrachlorvinphos',
    'tebuconazole': 'tebuconazole',
    'tebufenozide': 'tebufenozide',
    'teflubenzuron': 'teflubenzuron',
    'terpenes_total': 'total_terpenes',
    'terpinen4ol': 'terpinen_4_ol',
    'terpinen_4_ol': 'terpinen_4_ol',
    'terpineol': 'terpineol',
    'terpinolene': 'terpinolene',
    'tetrachlorvinphos': 'tetrachlorvinphos',
    'tetrafluoroethane': 'tetrafluoroethane',
    'tetrahydrocannabinol': 'delta_9_thc',
    'tetrahydrocannabinolic_acid': 'thca',
    'tetrahydrocannabinolic_acid_thca': 'thca',
    'tetrahydrocannabivarin': 'thcv',
    'tetrahydrocannabivarin_thcv': 'thcv',
    'tetrahydrocannabivarinic_acid': 'thcva',
    'tetrahydrocannabivarinic_acid_thcva': 'thcva',
    'tetramethrin': 'tetramethrin',
    'thc': 'delta_9_thc',
    'thc_a': 'thca',
    'thc_v': 'thcv',
    'thc_va': 'thcva',
    'thca': 'thca',
    'thca_a': 'thca',
    'thcv': 'thcv',
    'thcv_a': 'thcva',
    'thcva': 'thcva',
    'thiabendazol': 'thiabendazole',
    'thiabendazole': 'thiabendazole',
    'thiacloprid': 'thiacloprid',
    'thiaclorprid': 'thiacloprid',
    'thiamethoxam': 'thiamethoxam',
    'thiophanate_methyl': 'thiophanate_methyl',
    'thujone': 'thujone',
    'thymol': 'thymol',
    'toluene': 'toluene',
    'total_a_atoxins': 'total_aflatoxins',
    'total_abamectin': 'abamectin',
    'total_aerobic_bacteria': 'total_aerobic_bacteria',
    'total_aerobic_count': 'total_aerobic_bacteria',
    'total_aerobic_microbial_count': 'total_aerobic_bacteria',
    'total_aerobic_plate_count': 'total_aerobic_bacteria',
    'total_aflatoxin': 'total_aflatoxins',
    'total_aflatoxins': 'total_aflatoxins',
    'total_arsenic': 'arsenic',
    'total_bile_tolerant_gram_negative_bacteria': 'enterobacteriaceae',
    'total_butanes': 'total_butanes',
    'total_cannabinoids': 'total_cannabinoids',
    'total_cbd': 'total_cbd',
    'total_cbd_total_cbd_cbda_x_0_877_cbd': 'total_cbd',
    'total_coliform': 'total_coliforms',
    'total_coliforms': 'total_coliforms',
    'total_enterobacteriaceae': 'enterobacteriaceae',
    'total_hexanes': 'total_hexanes',
    'total_mercury': 'mercury',
    'total_mgk_264': 'mgk_264',
    'total_nerolidol': 'nerolidol',
    'total_of_aflatoxin_b_1_b_2_g_1_and_g_2': 'total_aflatoxins',
    'total_pentanes': 'total_pentanes',
    'total_permethrins': 'permethrin',
    'total_potential_thc': 'total_thc',
    'total_pyrethrins': 'pyrethrins',
    'total_sample_area_covered_by_an_imbedded_foreign_material': 'foreign_matter',
    'total_sample_area_covered_by_mold': 'total_yeast_and_mold',
    'total_sample_area_covered_by_sand_soil_cinders_or_dirt': 'soil',
    'total_spinosad': 'spinosad',
    'total_terpenes': 'total_terpenes',
    'total_terpineol': 'terpineol',
    'total_thc': 'total_thc',
    'total_thc_per_package': 'total_thc_per_package',
    'total_thc_total_thc_thca_x_0_877_thc': 'total_thc',
    'total_total_xylenes': 'total_xylenes',
    'total_viable_aerobic_bacteria': 'total_aerobic_bacteria',
    'total_viable_aerobic_bacteria_count': 'total_aerobic_bacteria',
    'total_viable_aerobic_count': 'total_aerobic_bacteria',
    'total_xylenes': 'total_xylenes',
    'total_yeast_and_mold': 'total_yeast_and_mold',
    'total_yeast_and_mold_count': 'total_yeast_and_mold',
    'total_yeast_mold': 'total_yeast_and_mold',
    'total_yeasttomold': 'total_yeast_and_mold',
    'trans_b_farnesene': 'trans_beta_farnesene',
    'trans_beta_famesene': 'trans_beta_farnesene',
    'trans_beta_farnesene': 'trans_beta_farnesene',
    'trans_caryophyllene': 'beta_caryophyllene',
    'trans_geraniol': 'geraniol',
    'trans_nerolidol': 'trans_nerolidol',
    'trans_ocimene': 'trans_ocimene',
    'trans_permethrin': 'trans_permethrin',
    'tri_oxystrobin': 'trifloxystrobin',
    'trichloroethane': 'trichloroethane',
    'trichloroethene': 'trichloroethylene',
    'trichloroethy_lene': 'trichloroethylene',
    'trichloroethylene': 'trichloroethylene',
    'trifloxystrob_in': 'trifloxystrobin',
    'trifloxystrobin': 'trifloxystrobin',
    'tym': 'total_yeast_and_mold',
    'tymc': 'total_yeast_and_mold',
    'valencene': 'valencene',
    'verbenone': 'verbenone',
    'visual_inspection': 'foreign_matter',
    'water_activity': 'water_activity',
    'xylenes': 'total_xylenes',
    'xylenes_total': 'total_xylenes',
    'yeast_and_mold': 'total_yeast_and_mold',
    'yeast_mold': 'total_yeast_and_mold',
    'ym': 'total_yeast_and_mold',
    'z_nerolidol': 'nerolidol',
}

def snake_case_analyte(label: str) -> str:
    """Snake-case a laboratory label the way the alias table expects.

    Greek letters are spelled out, accents folded, and every run of
    characters that is not a letter or digit becomes one underscore.

    Args:
        label: The label as printed on a certificate of analysis.

    Returns:
        An ASCII snake_case string, possibly empty.
    """
    text = str(label).strip()
    for symbol, spelled in _TRANSLITERATE.items():
        text = text.replace(symbol, spelled)
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')

def _separate_greek_digits(snake: str) -> str:
    """'delta8_thc' (from 'Δ8-THC') becomes 'delta_8_thc'."""
    return re.sub(r'(delta|alpha|beta|gamma)(\d)', r'\1_\2', snake)

def normalize_analyte_key(key: Optional[str]) -> Optional[str]:
    """Map any analyte label or key to its canonical key.

    Args:
        key: A label from a certificate of analysis (``'Δ9-THC'``,
            ``'beta-Myrcene'``, ``'Isopropanol'``) or an existing key.

    Returns:
        The canonical snake_case key. An unrecognised label is returned
        snake-cased, so that a new analyte is never lost, only
        unmapped. ``None`` and blank input return ``None``.
    """
    if key is None:
        return None
    snake = snake_case_analyte(key)
    if not snake:
        return None
    if snake in ANALYTE_ALIASES:
        return ANALYTE_ALIASES[snake]
    separated = _separate_greek_digits(snake)
    return ANALYTE_ALIASES.get(separated, separated)

def analysis_for_analyte(key: Optional[str]) -> Optional[str]:
    """Name the analysis a label or key belongs to, or ``None``."""
    return ANALYTE_TO_ANALYSIS.get(normalize_analyte_key(key))
