"""
State Variables | Cannlytics Console

Author: Keegan Skeate
Company: Cannlytics
Created: 10/15/2020
Updated: 7/30/2021

Relatively static state variables for extra context on each page/screen.
The idea is to separate the material from the templates,
with the hope of better-maintained code.
The data models are stored in an organizations settings, so that
each organization can customize the data points that they collect.
"""
# pylint:disable=line-too-long

#-----------------------------------------------------------------------
# Data, page-specific supplementary data. (loaded from Firestore)
# FIXME: Currently not implemented in views/main.py
#-----------------------------------------------------------------------

data = {
    "settings": {
        "documents": [
            {"key": "traceability_settings", "ref": "organizations/{organization_id}/organization_settings/traceability_settings"},
        ],
        "collections": [
            {"key": "data_models", "ref": "organizations/{organization_id}/data_models"},
        ],
    },
}

#-----------------------------------------------------------------------
# Data models
# Optional: Add the following fields.
#     - current_count
#     - placeholder
#         * action, height, image, message, title, url
#-----------------------------------------------------------------------

data_models = [
    {
        "label": "Dashboard",
        "url": "/",
        "icon": "grid",
        "key": "",
        "user_type": "*",
        "major": True,
        "hidden": True,
    },
    {
        "label": "Analytics",
        "url": "/analytics",
        "key": "analytics",
        "user_type": ["producer", "processor", "retailer",
            "consumer", "integrator"],
        "image_path": "console/images/icons/two-tone/two_tone_graph.svg",
        "description": "Explore rich analytics to better understand your choices and performance.",
        "seperator": True
    },
    {
        "label": "Analyses",
        "url": "/analyses",
        "key": "analyses",
        "user_type": "lab",
        "description": "Manage analyses, tests for your analytes.",
        "image_path": "console/images/icons/multi-tone/certificate-flask.svg",
        "seperator": True,
        'singular': 'analysis',
        'sortable': True,
        'filter': True,
        'abbreviation': 'AN',
        'id_schema': '[abbreviation]%y%m%d',
        "fields": [
            {"key": "analysis_id", "label": "Analysis ID"},
            {"key": "name", "label": "Name"},
            {"key": "key", "label": "Key"},
            {"key": "price", "label": "Price", "type": "text", "class": "field-sm"}, # Optional: currency
            {"key": "public", "label": "Public", "type": "bool"},
            # TODO: Add analytes (list)
        ],
    },
    {
        "label": "Analytes",
        "url": "/analytes",
        "key": "analytes",
        "user_type": "lab",
        "description": "Manage analytes, compounds that you wish to measure.",
        "image_path": "console/images/icons/multi-tone/microscope.svg",
        'abbreviation': 'AT',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'analyte',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "analyte_id", "label": "Analyte ID"},
            {"key": "name", "label": "Name"},
            {"key": "key", "label": "Key"},
            {"key": "formula", "label": "Formula", "type": "text"},
            {"key": "limit", "label": "Limit", "type": "number", "class":"field-sm text-end"},
            {"key": "lod", "label": "LOD", "type": "number", "class":"field-sm text-end"},
            {"key": "loq", "label": "LOQ", "type": "number", "class":"field-sm text-end"},
            {"key": "result_units", "label": "Result Units", "type": "text", "class":"field-sm"},
            {"key": "measurement_units", "label": "Measurement Units", "type": "text", "class":"field-sm"},
            {"key": "cas", "label": "CAS Number", "class":"field-sm"},
            {"key": "public", "label": "Public", "type": "bool"},
        ],
    },
    {
        "label": "Areas",
        "url": "/areas",
        "key": "areas",
        "user_type": "lab",
        "description": "Manage facilities and locations.",
        "image_path": "console/images/icons/multi-tone/lab.svg",
        'abbreviation': 'AR',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'area',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "area_id", "label": "Area ID"},
            {"key": "name", "label": "Name"},
            {"key": "area_type", "label": "Area Type", "type": "select", "options": [{"key": "Default", "label": "Default"}, {"key": "Planting", "label": "Planting"}, {"key": "Packing", "label": "Packing"}], "selected": "Default"},
            {"key": "area_type_id", "label": "Area Type ID", "type": "select", "options": [{"key": "1", "label": "1"}, {"key": "2", "label": "2"}, {"key": "3", "label": "3"}], "selected": "1"},
            {"key": "external_id", "label": "External ID"},
            {"key": "active", "label": "Active", "type": "bool"},
            {"key": "quarantine", "label": "Quarantine", "type": "bool"},
        ],
    },
    {
        "label": "Contacts",
        "url": "/contacts",
        "key": "contacts",
        "user_type": '*',
        "description": "Manage laboratory clients, vendors, and relations.",
        "image_path": "console/images/icons/multi-tone/clients.svg",
        'abbreviation': 'CT',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'contact',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "contact_id", "label": "Contact ID"},
            {"key": "organization", "label": "Organization"},
            {"key": "trade_name", "label": "Trade Name"},
            {"key": "email", "label": "Email", "type": "email"},
            {"key": "phone", "label": "Phone Number", "type": "tel"},
            {"key": "website", "label": "Website"},
            {"key": "address", "label": "Address"},
            {"key": "street", "label": "Street"},
            {"key": "city", "label": "City"},
            {"key": "county", "label": "County"},
            {"key": "state", "label": "State", "class": "field-sm"},
            {"key": "zip_code", "label": "Zip", "class": "field-sm"},
            {"key": "latitude", "label": "Latitude", "type": "number", "class": "field-sm"},
            {"key": "longitude", "label": "Longitude", "type": "number", "class": "field-sm"},
            {"key": "billing_address", "label": "Billing Address"},
            {"key": "billing_city", "label": "Billing City"},
            {"key": "billing_state", "label": "Billing State", "class": "field-sm"},
            {"key": "billing_zip_code", "label": "Billing Zip Code", "class": "field-sm"},
            {"key": "billing_email", "label": "Billing Email"},
            # TODO: Add people (list)
        ],
    },
    {
        "label": "Instruments",
        "url": "/instruments",
        "key": "instruments",
        "user_type": "lab",
        "description": "Manage scientific instruments.",
        "image_path": "console/images/icons/multi-tone/analysis.svg",
        'abbreviation': 'IS',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'instrument',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "instrument_id", "label": "Instrument ID"},
            {"key": "name", "label": "Name"},
            {"key": "vendor", "label": "Vendor", "type": "text"},
            {"key": "instrument_type", "label": "Instrument Type", "type": "text"},
            {"key": "analyses", "label": "Analyses", "type": "text"},
            {"key": "data_path", "label": "Data path"},
            {"key": "area_id", "label": "Area ID"},
            {"key": "area_name", "label": "Area Name"},
            {"key": "calibrated_at", "label": "Calibrated At", "type": "datetime"},
            {"key": "calibrated_by", "label": "Calibrated By", "class": "field-sm"},
            {"key": "description", "label": "Description", "type": "textarea"},
            
        ],
    },
    {
        "label": "Inventory",
        "url": "/inventory",
        "key": "inventory",
        "user_type": "lab",
        "description": "Manage inventory, items, packages, and more.",
        "image_path": "console/images/icons/multi-tone/records.svg",
        'abbreviation': 'IN',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'item',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "item_id", "label": "Item ID"}, # Optional: inventory_id is preferred but bug in app.js createID prevents this.
            {"key": "name", "label": "Name"},
            {"key": "item_type", "label": "Item Type", "type": "text"},
            {"key": "quantity", "label": "Quantity", "type": "text"},
            {"key": "quantity_type", "label": "Quantity Type", "type": "text"},
            {"key": "admin_method", "label": "Admin Method", "type": ""},
            {"key": "approved", "label": "Approved", "type": ""},
            {"key": "approved_at", "label": "Approved At", "type": "datetime"},
            {"key": "moved_at", "label": "Moved At", "type": "datetime"},
            {"key": "area_id", "label": "Area ID", "type": ""},
            {"key": "area_name", "label": "Area Name", "type": ""},
            {"key": "category_name", "label": "Category Name", "type": ""},
            {"key": "category_type", "label": "Category Type", "type": ""},
            {"key": "strain_name", "label": "Strain Name"},
            {"key": "status", "label": "Status", "type": ""},
            {"key": "description", "label": "Description", "type": "textarea"},
            {"key": "dose", "label": "Dose", "type": "number", "class": "field-sm"},
            {"key": "dose_number", "label": "Dose Number", "type": "number", "class": "field-sm"},
            {"key": "dose_units", "label": "Dose Units", "type": "text", "class": "field-sm"},
            {"key": "serving_size", "label": "Serving Size", "type": "number", "class": "field-sm"},
            {"key": "supply_duration_days", "label": "Supplay Duration in Days", "type": "number", "class": "field-sm"},
            {"key": "units", "label": "Units", "class": "field-sm"},
            {"key": "volume", "label": "Volume", "type": "number", "class": "field-sm"},
            {"key": "volume_units", "label": "Volume Units", "class": "field-sm"},
            {"key": "weight", "label": "Weight", "type": "number", "class": "field-sm"},
            {"key": "weight_units", "label": "Weight Units", "class": "field-sm"},
        ],
    },
    {
        "label": "Invoices",
        "url": "/invoices",
        "key": "invoices",
        "user_type": "*",
        "user_permissions": ["billing"],
        "description": "Manage invoices for your laboratory analyses.",
        "image_path": "console/images/icons/multi-tone/notes.svg",
        'abbreviation': 'IV',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'invoice',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "invoice_id", "label": "Invoice ID"},
            {"key": "organization", "label": "Organization"},
            {"key": "billing_address", "label": "Billing Address"},
            {"key": "billing_city", "label": "Billing City"},
            {"key": "billing_state", "label": "Billing State", "class": "field-sm"},
            {"key": "billing_zip_code", "label": "Billing Zip Code", "class": "field-sm"},
            {"key": "billing_email", "label": "Billing Email"},
            {"key": "status", "label": "Status", "type": "select", "options": [{"key": "unpaid", "label": "Unpaid"}, {"key": "paid", "label": "Paid"}]},
            {"key": "total", "label": "Total ($)", "type": "number", "class": "field-sm"},
            {"key": "currency", "label": "Currency", "class": "field-sm"},
            {"key": "due_at", "label": "Due At", "type": "datetime"},
            {"key": "created_at", "label": "Created At", "type": "datetime"},
            {"key": "created_by", "label": "Created By", "class": "field-sm"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "label": "Measurements",
        "url": "/measurements",
        "key": "measurements",
        "user_type": "lab",
        "description": "Manage measurements by analysts and from your instruments.",
        "image_path": "console/images/icons/multi-tone/abacus.svg",
        'abbreviation': 'MT',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'measurement',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "measurement_id", "label": "Measurement ID"},
            {"key": "sample_id", "label": "Sample ID"},
            {"key": "sample_name", "label": "Sample Name"},
            {"key": "sample_mass", "label": "Sample Mass", "type": "number", "class": "field-sm"},
            {"key": "dilution_factor", "label": "Dilution Factor", "type": "number", "class": "field-sm"},
            {"key": "units", "label": "Units", "class": "field-sm"},
            {"key": "final", "label": "Final", "type": "bool"},
            {"key": "sample_type", "label": "Sample Type"},
            {"key": "created_at", "label": "Created At", "type": "datetime"},
            {"key": "created_by", "label": "Created By", "class": "field-sm"},
            # {"key": "measurement", "label": "Measurement", "type": "number", "class": "field-sm"},
            # {"key": "measurement_units", "label": "Measurement Units", "class": "field-sm"},
            {"key": "instrument_id", "label": "Instrument ID"},
            # {"key": "instrument", "label": "Instrument"},
            # {"key": "analyte_id", "label": "Analyte ID"},
            # {"key": "analyte", "label": "Analyte"},
            {"key": "analysis_id", "label": "Analysis ID"},
            # {"key": "analysis", "label": "Analysis"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "label": "Projects",
        "url": "/projects",
        "key": "projects",
        "user_type": "*",
        "description": "Manage your internal and external projects.",
        "image_path": "console/images/icons/multi-tone/folder.svg",
        'abbreviation': 'P',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'project',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "project_id", "label": "Project ID"},
            {"key": "organization", "label": "Organization"},
            {"key": "transfer_ids", "label": "Transfer IDs", "type": "text"},
            {"key": "received_at", "label": "Received At", "type": "datetime"},
            {"key": "created_at", "label": "Created At", "type": "datetime"},
            {"key": "created_by", "label": "Created By", "class": "field-sm"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "label": "Purchases",
        "url": "/purchases",
        "icon": "shoping-bag",
        "key": "purchases",
        "user_type": ["consumer"],
    },
    {
        "label": "Results",
        "url": "/results",
        "key": "results",
        "user_type": "*",
        "description": "Manage laboratory results.",
        "image_path": "console/images/icons/multi-tone/certificate.svg",
        'abbreviation': 'R',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'result',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "result_id", "label": "Result ID"},
            {"key": "analyte", "label": "Analyte"},
            {"key": "measurement", "label": "Measurement"},
            {"key": "sample_mass", "label": "Sample Mass", "type": "number", "class": "field-sm"},
            {"key": "dilution_factor", "label": "Dilution Factor", "type": "number", "class": "field-sm"},
            {"key": "result", "label": "Result", "type": "number", "class": "field-sm"},
            {"key": "units", "label": "Units", "class": "field-sm"},
            {"key": "status", "label": "Status", "class": "field-sm"},
            {"key": "formula", "label": "Formula", "type": "formula"},
            # {"key": "sample_id", "label": "Sample ID"},
            # {"key": "package_id", "label": "Package ID"},
            # {"key": "package_label", "label": "Package Label"},
            # {"key": "sample_name", "label": "Sample Name"},
            # {"key": "sample_type", "label": "Sample Type"},
            {"key": "reviewed_at", "label": "Reviewed At", "type": "datetime"},
            {"key": "reviewed_by", "label": "Reviewed By", "class": "field-sm"},
            {"key": "approved_at", "label": "Approved At", "type": "datetime"},
            {"key": "approved_by", "label": "Approved By", "class": "field-sm"},
            {"key": "tested_at", "label": "Tested At", "type": "datetime"},
            {"key": "voided_at", "label": "Voided At", "type": "datetime"}, # TODO: Only show given a value
            {"key": "released_at", "label": "Released At", "type": "datetime"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
            {"key": "non_mandatory", "label": "Non-mandatory", "type": "bool"},
            {"key": "released", "label": "Released", "type": "bool"},

        ],
    },
    {
        "label": "Samples",
        "url": "/samples",
        "key": "samples",
        "user_type": "*",
        "description": "Manage laboratory samples.",
        "image_path": "console/images/icons/multi-tone/vials.svg",
        'abbreviation': 'S',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'sample',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "sample_id", "label": "Sample ID"},
            {"key": "project_id", "label": "Project ID"},
            {"key": "batch_id", "label": "Batch ID"},
            {"key": "sample_name", "label": "Sample Name"},
            {"key": "strain_name", "label": "Strain Name"},
            {"key": "sample_type", "label": "Sample Type"},
            {"key": "created_at", "label": "Created At", "type": "datetime"},
            {"key": "created_by", "label": "Created By", "class": "field-sm"},
            {"key": "updated_at", "label": "Updated At", "type": "datetime"},
            {"key": "updated_by", "label": "Updated By", "class": "field-sm"},
            {"key": "coa_url", "label": "CoA URL", "type": "text"},
            {"key": "coa_ref", "label": "CoA Ref", "type": "text", "hidden": True},
            {"key": "coa_status", "label": "CoA Status", "type": "select", "options": [{"key": "unreviewed", "label": "Unreviewed"}, {"key": "reviewed", "label": "Reviewed"}, {"key": "approved", "label": "Approved"}, {"key": "released", "label": "Released"},]},
            {"key": "notes", "label": "Notes", "type": "textarea"},
            {"key": "photo_url", "label": "Photo", "type": "image"},
        ],
    },
    {
        "label": "Transfers",
        "url": "/transfers",
        "key": "transfers",
        "user_type": '*',
        "description": "Manage sample transfers.",
        "image_path": "console/images/icons/multi-tone/transmit.svg",
        'abbreviation': 'TR',
        'id_schema': '[abbreviation]%y%m%d',
        'singular': 'transfer',
        'sortable': True,
        'filter': True,
        "fields": [
            {"key": "receiver", "label": "Receiver", "type": "select"},
            {"key": "receiver_org_id", "label": "Receiver Organization ID", "hidden": True},
            {"key": "sender", "label": "Sender", "hidden": True},
            {"key": "sender_org_id", "label": "Sender Organization ID", "hidden": True},
            {"key": "transfer_id", "label": "Transfer ID"},
            {"key": "transfer_type", "label": "Transfer Type", "type": "select", "options": [{"key": "Lab Sample Transfer", "label": "Lab Sample Transfer"}]},
            {"key": "transfer_url", "label": "Manifest Photo", "type": "image"},
            {"key": "status", "label": "Status", "type": "select", "options": [{"key": "Shipped", "label": "Shipped"}, {"key": "Rejected", "label": "Rejected"}, {"key": "Accepted", "label": "Accepted"}, {"key": "Returned", "label": "Returned"}]},
            {"key": "departed_at", "label": "Estimated Departure", "type": "datetime"},
            {"key": "arrived_at", "label": "Estimated Arrival", "type": "datetime"},
            {"key": "sample_count", "label": "Sample Count", "type": "number", "class": "field-sm"},
            {"key": "transporter", "label": "Transporter", "type": "select"},
            {"key": "vehicle", "label": "Vehicle", "type": "select"},
        ],
        "metrc_fields": [
            {"key": "actual_arrival_date_time", "label": "Actual Arrival Date Time"},
            {"key": "actual_departure_date_time", "label": "Actual Departure Date Time"},
            {"key": "actual_return_arrival_date_time", "label": "Actual Return Arrival Date Time"},
            {"key": "actual_return_departure_date_time", "label": "Actual Return Departure Date Time"},
            {"key": "contains_donation", "label": "Contains Donation"},
            {"key": "contains_plant_package", "label": "Contains Plant Package"},
            {"key": "contains_product_package", "label": "Contains Product Package"},
            {"key": "contains_product_requires_remediation", "label": "Contains Product Requires Remediation"},
            {"key": "contains_remediated_product_package", "label": "Contains Remediated Product Package"},
            {"key": "contains_testing_sample", "label": "Contains Testing Sample"},
            {"key": "contains_trade_sample", "label": "Contains Trade Sample"},
            {"key": "created_by_user_name", "label": "Created By User Name"},
            {"key": "created_date_time", "label": "Created Date Time"},
            {"key": "delivery_count", "label": "Delivery Count"},
            {"key": "delivery_id", "label": "Delivery Id"},
            {"key": "delivery_package_count", "label": "Delivery Package Count"},
            {"key": "delivery_received_package_count", "label": "Delivery Received Package Count"},
            {"key": "driver_name", "label": "Driver Name"},
            {"key": "driver_occupational_license_number", "label": "Driver Occupational License Number"},
            {"key": "driver_vehicle_license_number", "label": "Driver Vehicle License Number"},
            {"key": "estimated_arrival_date_time", "label": "Estimated Arrival Date Time"},
            {"key": "estimated_departure_date_time", "label": "Estimated Departure Date Time"},
            {"key": "estimated_return_arrival_date_time", "label": "Estimated Return Arrival Date Time"},
            {"key": "estimated_return_departure_date_time", "label": "Estimated Return Departure Date Time"},
            {"key": "id", "label": "Id"},
            {"key": "last_modified", "label": "Last Modified"},
            {"key": "manifest_number", "label": "Manifest Number"},
            {"key": "name", "label": "Name"},
            {"key": "package_count", "label": "Package Count"},
            {"key": "received_date_time", "label": "Received Date Time"},
            {"key": "received_delivery_count", "label": "Received Delivery Count"},
            {"key": "received_package_count", "label": "Received Package Count"},
            {"key": "recipient_facility_license_number", "label": "Recipient Facility License Number"},
            {"key": "recipient_facility_name", "label": "Recipient Facility Name"},
            {"key": "shipment_license_type", "label": "Shipment License Type"},
            {"key": "shipment_transaction_type", "label": "Shipment Transaction Type"},
            {"key": "shipment_type_name", "label": "Shipment Type Name"},
            {"key": "shipper_facility_license_number", "label": "Shipper Facility License Number"},
            {"key": "shipper_facility_name", "label": "Shipper Facility Name"},
            {"key": "transporter_facility_license_number", "label": "Transporter Facility License Number"},
            {"key": "transporter_facility_name", "label": "Transporter Facility Name"},
            {"key": "vehicle_license_plate_number", "label": "Vehicle License Plate Number"},
            {"key": "vehicle_make", "label": "Vehicle Make"},
            {"key": "vehicle_model", "label": "Vehicle Model"},
        ],
    },
    {
        "label": "Traceability",
        "url": "/traceability",
        "icon": "share-2",
        "key": "traceability",
        "user_type": "*",
        "seperator": True,
        "major": True,
        "description": "Manage traceability integration and view audit logs.",
        "image_path": "console/images/icons/multi-tone/certificate-access.svg",
    },
    {
        "label": "Settings",
        "url": "/settings",
        "icon": "settings",
        "key": "settings",
        "user_type": "*",
        "major": True,
        "description": "Manage your user and organization settings.",
        "image_path": "console/images/icons/two-tone/two_tone_gears.svg",
    },
    {
        "label": "Help",
        "url": "/help",
        "icon": "help-circle",
        "key": "help",
        "user_type": "*",
        "major": True,
        "hidden": True,
    },
    {
        'label': 'Logs',
        'key': 'logs',
        'singular': 'log',
        'abbreviation': 'L',
        'id_schema': '[abbreviation]%y%m%d',
        'sortable': True,
        'filter': True,
        'hidden': True,
        "fields": [
            {"key": "created_at", "label": "Time", "type": "datetime", "class": "field-sm"},
            {"key": "log_id", "label": "Log ID", "disabled": True, "hidden": True},
            {"key": "action", "label": "Action"},
            {"key": "changes", "label": "Changes", "type": "textarea"},
            {"key": "user", "label": "User ID", "disabled": True},
            {"key": "user_email", "label": "User email", "disabled": True},
            {"key": "user_name", "label": "User name", "disabled": True},
            {"key": "user_photo_url", "label": "User photo", "disabled": True},
            {"key": "type", "label": "Type", "class": "field-sm", "disabled": True},
            {"key": "key", "label": "Key", "class": "field-sm", "disabled": True},
        ],
    },
    {
        'label': 'Files',
        'key': 'files',
        'singular': 'file',
        'abbreviation': 'F',
        'id_schema': '[abbreviation]%y%m%d',
        'sortable': True,
        'filter': True,
        'hidden': True,
        "fields": [
            {"key": "file_id", "label": "File ID", "disabled": True, "hidden": True},
            {"key": "name", "label": "Name", "disabled": True},
            {"key": "uploaded_at", "label": "Uploaded At", "type": "datetime", "disabled": True},
            {"key": "uploaded_by", "label": "Uploaded By", "disabled": True},
            {"key": "content_type", "label": "File Type", "disabled": True},
            {"key": "file_size", "label": "File Size", "disabled": True},
            {"key": "version", "label": "Version", "class": "field-sm", "disabled": True},
            {"key": "type", "label": "Type", "class": "field-sm", "disabled": True},
            {"key": "key", "label": "Key", "class": "field-sm", "disabled": True},
            {"key": "pinned", "label": "Pin File", "type": "bool", "onchange": "pinFile"},
        ],
    },
    {
        'label': 'People',
        'key': 'people',
        'singular': 'person',
        'abbreviation': 'USR',
        'description': 'Manage people associated with a given contact.',
        "image_path": "console/images/icons/outline/teamwork.svg",
        'id_schema': '[abbreviation]%y%m%d',
        'sortable': True,
        'filter': True,
        'hidden': True,
        "fields": [
            {"key": "person_id", "label": "Person ID"},
            {"key": "name", "label": "Name"},
            {"key": "email", "label": "Email"},
            {"key": "phone", "label": "Phone"},
            {"key": "position", "label": "Position"},
            {"key": "result_recipient", "label": "Result Recipient", "type": "bool"},
            {"key": "billing_contact", "label": "Billing Contact", "type": "bool"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
]

#-----------------------------------------------------------------------
# Material, page-specific context.
#-----------------------------------------------------------------------

material = {
    "analyses": {
        "placeholder": {
            "action": "Create an analysis",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_microbiologist.svg",
            "title": "Create your first analysis",
            "message": "Create a scientific analysis, a set of analytes or tests to collect measurements for to get results.",
            "url": "./analyses/new",
        },
    },
    "analytes": {
        "placeholder": {
            "action": "Create an analyte",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_microscope.svg",
            "title": "Create your first analyte",
            "message": "Add analytes for analyses, a set of analytes constitutes an analysis. Analytes can have limits and formulas for calculating results.",
            "url": "./analytes/new",
        },
    },
    "areas": {
        "placeholder": {
            "action": "Create an area",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_books.svg",
            "title": "Create your first area",
            "message": "Organize your company and facilities into logical areas so you can easily manage the location of your physical items.",
            "url": "./areas/new",
        },
    },
    "contacts": {
        "placeholder": {
            "action": "Add a contact",
            "height": "200px",
            "image": "console/images/illustrations/chemistry_scientist.svg",
            "title": "Add your first contact",
            "message": "Add a contact to begin providing analyses for other organizations. Contacts are any other organization you interact with, such as your clients, vendors, and partners.",
            "url": "./contacts/new",
        },
    },
    "instruments": {
        "placeholder": {
            "action": "Connect an instrument",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab.svg",
            "title": "Connect your first instrument",
            "message": "Connect your scientific instruments to ease your data collection.",
            "url": "./instruments/new",
        },
    },
    "inventory": {
        "placeholder": {
            "action": "Add an inventory item",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_reagents.svg",
            "title": "Add your first inventory item",
            "message": "Track your inventory through your analysis workflow.",
            "url": "./inventory/new",
        },
    },
    "invoices": {
        "placeholder": {
            "action": "Add an invoice",
            "height": "200px",
            "image": "console/images/icons/multi-tone/folder.svg",
            "title": "Add your first invoice",
            "message": "Invoice contacts for their analyses requested.",
            "url": "./invoices/new",
        },
    },
    "measurements": {
        "placeholder": {
            "action": "Add a measurement",
            "height": "200px",
            "image": "console/images/icons/two-tone/two_tone_stats.svg",
            "title": "Add your first measurement",
            "message": "Do your analyses by adding measurements, inputs for analyte formulas to calculate final results.",
            "url": "./measurements/new",
        },
    },
    "projects": {
        "placeholder": {
            "action": "Create a project",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_tablet.svg",
            "title": "Create your first project",
            "message": "Begin analyses by creating a project, a collection of an organization's samples and their analyses.",
            "url": "./projects/new",
        },
    },
    "results": {
        "placeholder": {
            "action": "Calculate your first result",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_reagents.svg",
            "title": "Calculate your first result",
            "message": "Calculate your first result given analyses performed and data collected.",
            "url": "./results/new",
        },
    },
    "samples": {
        "placeholder": {
            "action": "Create a sample",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_reagents.svg",
            "title": "Create your first laboratory sample",
            "message": "Create laboratory samples which can be part of organization specific projects or multi-organization batches for analysis.",
            "url": "./samples/new",
        },
    },
    "transfers": {
        "placeholder": {
            "action": "Create an transfer",
            "height": "200px",
            "image": "console/images/illustrations/outline/lab_reagents.svg",
            "title": "Create your first transfer",
            "message": "Create a transfer of inventory items, such as lab samples, from one organization to another.",
            "url": "./transfers/new",
        },
    },
    "transporters": {
        "placeholder": {
            "height": "200px",
            "image": "console/images/icons/two-tone/two_tone_report.svg",
            "title": "No transporter data",
            "message": "You can add information here about the people who will be transporting your products.",
        },
        "fields": [
            {"key": "transporter_id", "label": "Transporter ID"},
            {"key": "driver_name", "label": "Driver Name"},
            {"key": "driver_occupational_license_number", "label": "Driver Occupational License Number"},
            {"key": "transporter_facility_license_number", "label": "Transporter Facility License Number"},
            {"key": "transporter_facility_name", "label": "Transporter Facility Name"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    "vehicles": {
        "placeholder": {
            "height": "200px",
            "image": "console/images/icons/two-tone/two_tone_clock.svg",
            "title": "No vehicle data",
            "message": "You can add information here about the vehicles that transport your products.",
        },
        "fields": [
            {"key": "vehicle_id", "label": "Vehicle ID"},
            {"key": "vehicle_make", "label": "Vehicle Make"},
            {"key": "vehicle_model", "label": "Vehicle Model"},
            {"key": "vehicle_color", "label": "Vehicle Color"},
            {"key": "vehicle_license_plate_number", "label": "Vehicle License Plate Number"},
            {"key": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    "traceability": {
        "provider": "Metrc",
        "tabs": [
            {
                "name": "Items",
                "section": "items",
                "url": "/traceability/items",
                "description": "View items that are used to track your inventory at a given facility.",
                "org_types": ["producer", "retailer"],
                "selected": False,
            },
            {
                "name": "Packages",
                "section": "packages",
                "url": "/traceability/packages",
                "description": "Manage your packages, groups of cannabis items.",
                "org_types": ["lab", "producer", "retailer"],
                "selected": True,
            },
            {
                "name": "Lab Tests",
                "section": "lab-tests",
                "url": "/traceability/lab-tests",
                "description": "Manage details for each individual lab test performed on submitted packages.",
                "org_types": ["lab", "producer", "retailer"],
                "selected": True,
            },
            {
                "name": "Strains",
                "section": "strains",
                "url": "/traceability/strains",
                "description": "View your cannabis strains, varieties, and classifications.",
                "org_types": ["producer", "retailer"],
                "selected": False,
            },
            {
                "name": "Employees",
                "section": "employees",
                "url": "/traceability/employees",
                "description": "View your organization's employees or team members.",
                "org_types": [],
                "selected": False,
            },
            {
                "name": "Facilities",
                "section": "facilities",
                "url": "/traceability/facilities",
                "description": "",
                "org_types": [],
                "selected": False,
            },
            {
                "name": "Locations",
                "section": "locations",
                "url": "/traceability/locations",
                "description": "Manage your locations used track packages and items.",
                "org_types": ["lab", "producer", "retailer"],
                "selected": True,
            },
            {
                "name": "Harvests",
                "section": "harvests",
                "url": "/traceability/harvests",
                "org_types": ["producer"],
                "selected": False,
            },
            {
                "name": "Patients",
                "section": "patients",
                "url": "/traceability/patients",
                "org_types": ["retailer"],
                "selected": False,
            },
            {
                "name": "Plant Batches",
                "section": "plant-batches",
                "url": "/traceability/plant-batches",
                "org_types": ["producer"],
                "selected": False,
            },
            {
                "name": "Plants",
                "section": "plants",
                "url": "/traceability/plants",
                "org_types": ["producer"],
                "selected": False,
            },
            {
                "name": "Sales",
                "section": "sales",
                "url": "/traceability/sales",
                "org_types": ["retailer"],
                "selected": False,
            },
            {
                "name": "Transfers",
                "section": "transfers",
                "url": "/traceability/transfers",
                "description": "Manage your records of packages moving from one licensee to another.",
                "org_types": ["lab", "producer", "retailer"],
                "selected": True,
            },
            {
                "name": "Units",
                "section": "units",
                "url": "/traceability/units",
                "description": "",
                "org_types": [],
                "selected": False,
            },
            {
                "name": "Settings",
                "section": "settings",
                "url": "/traceability/settings",
                "description": "Manage the settings of your interface to your traceability system.",
                "org_types": ["lab", "producer", "retailer", "integrator"],
                "selected": True,
            },
        ],
    },
    "settings": {
        # TODO: Add remaining settings.
        "options": [
            {"title": "API", "url": "/settings/api"},
            # {"title": "Data", "url": "/settings/data"},
            # {"title": "Logs", "url": "/settings/logs"},
            # {"title": "Notifications", "url": "/settings/notifications"},
            {"title": "Organization settings", "url": "/settings/organizations"},
            # {"title": "Theme", "url": "/settings/theme"},
            {"title": "User Settings", "url": "/settings/user"},
        ],
        "organizations": {
            "breadcrumbs": [
                {"title": "Settings", "url": "settings"},
                {"title": "Organizations", "active": True},
            ],
            "fields": [
                {"key": "name", "label": "Name"},
                {"key": "trade_name", "label": "Trade Name"},
                {"key": "website", "label": "Website"},
                {"type": "email", "key": "email", "label": "Email"},
                {"key": "phone", "label": "Phone"},
                {"key": "linkedin", "label": "LinkedIn"},
                {"key": "address", "label": "Address", "secondary": True},
                {"key": "city", "label": "City", "secondary": True},
                {"key": "state", "label": "State", "secondary": True},
                {"key": "country", "label": "Country", "secondary": True},
                {"key": "zip_code", "label": "Zip Code", "secondary": True},
                {"key": "external_id", "label": "External ID", "secondary": True},
            ],
            "placeholder": {
                "action": "Start an organization",
                "height": "200px",
                "image": "console/images/illustrations/chemistry_scientist.svg",
                "title": "Create or join an organization",
                "message": "Add team members to your organization or join an organization to begin collaborating.",
                "url": "./organizations/new",
            },
        },
        "organization_breadcrumbs": [
            {"title": "Settings", "url": "settings"},
            {"title": "Organization Settings", "active": True},
        ],
        "user_breadcrumbs": [
            {"title": "Settings", "url": "settings"},
            {"title": "User Settings", "active": True},
        ],
        "user_fields": [
            {"key": "name", "label": "Name"},
            {"key": "position", "label": "Position"},
            {"type": "email", "key": "email", "label": "Email"},
            {"key": "phone_number", "label": "Phone"},
            {"key": "license", "label": "License"},
        ],
        "user_options": [
            {"title": "Change your password", "url": "/account/password-reset"},
        ],
    },
    "logs": {
        "placeholder": {
            "height": "200px",
            "image": "console/images/icons/multi-tone/documents.svg",
            "title": "No logs in this period",
            "message": "You can create a custom log for traceability or quality control purposes or try expanding your search.",
        },
        "fields": [
            {"key": "created_at", "label": "Time", "type": "datetime", "class": "field-sm"},
            {"key": "log_id", "label": "Log ID", "disabled": True, "hidden": True},
            {"key": "action", "label": "Action"},
            {"key": "changes", "label": "Changes", "type": "textarea"},
            {"key": "user", "label": "User ID", "disabled": True},
            {"key": "user_email", "label": "User email", "disabled": True},
            {"key": "user_name", "label": "User name", "disabled": True},
            {"key": "user_photo_url", "label": "User photo", "disabled": True},
            {"key": "type", "label": "Type", "class": "field-sm", "disabled": True},
            {"key": "key", "label": "Key", "class": "field-sm", "disabled": True},
        ],
    },
    "files": {
        "placeholder": {
            "height": "200px",
            "image": "console/images/icons/multi-tone/documents.svg",
            "title": "No logs in this period",
            "message": "You can create a custom log for traceability or quality control purposes or try expanding your search.",
        },
        "fields": [
            {"key": "file_id", "label": "File ID", "disabled": True, "hidden": True},
            {"key": "name", "label": "Name", "disabled": True},
            {"key": "uploaded_at", "label": "Uploaded At", "type": "datetime", "disabled": True},
            {"key": "uploaded_by", "label": "Uploaded By", "disabled": True},
            {"key": "content_type", "label": "File Type", "disabled": True},
            {"key": "file_size", "label": "File Size", "disabled": True},
            {"key": "version", "label": "Version", "class": "field-sm", "disabled": True},
            {"key": "type", "label": "Type", "class": "field-sm", "disabled": True},
            {"key": "key", "label": "Key", "class": "field-sm", "disabled": True},
            {"key": "pinned", "label": "Pin File", "type": "bool", "onchange": "pinFile"},
        ],
    },
}

# Getting-started material.
material['get-started'] = {
    "user": {"fields": material['settings']['user_fields']},
    "organization": {"fields": material['settings']['organizations']['fields']},
    "pricing_tiers": [
        {
            "name": "Enterprise",
            "price": "$2000 / mo.",
            "color": "purple",
            "action": "Contact us",
            "url": "/contact",
            "attributes": [
                "Custom installation",
                "Access to internal tools",
                "Early access to new features",
                "3 on-site support days / year",
            ],
        },
        {
            "name": "Pro",
            "price": "$500 / mo.",
            "color": "orange",
            "action": "Get started",
            "url": "/contact",
            "attributes": [
                "Metrc integration",
                "Access to development builds",
                "Priority GitHub Issues",
                "Remote support",
            ],
        },
        {
            "name": "Free",
            "price": "👐",
            "color": "green",
            "action": "Sign up for free",
            "url": "https://console.cannlytics.com",
            "attributes": [
                "All software",
                "All community material",
                "GitHub Issues",
                "Email support",
            ],
        },
    ],
}

# FIXME: Condense state so this data does not have to be duplicated.
material['settings']['traceability'] = material['traceability']
material['settings']['subscriptions'] = material['get-started']['pricing_tiers']

#-----------------------------------------------------------------------
# Layout context, context for general template rendering.
#-----------------------------------------------------------------------

layout = {
    "dashboard": {
        "welcome_message": {
            "title": "Welcome to your new cannabis analytics platform!", # 🚀
            "message": "Get started with cannabis analytics in 5 minutes.",
        },
        "organization_choices": [
            {
                "action": "Get started",
                "title": "🥼 For Labs",
                "description": "Start your lab workflow, manage your lab data, and issue your certificates. Start or join a lab. You can utilize the Cannlytics platform to manage all of your laboratory data and deliver data and certificates blazingly fast. Use your own workflow and data points, while using ready-to-go tools built for cannabis analysis.",
                "image": "console/images/illustrations/outline/lab_tablet.svg",
                "type": "lab",
            },
            {
                "action": "Begin now",
                "title": "🌳 For Cultivators, Processors, and Retailers",
                "description": "Start managing your lab results now. You can utilize the Cannlytics platform to make testing simple, easy, and insightful. Aggregate your data points and leverage statistics to boost your yields. Don't leave money on the table, get and use the laboratory data for tests that you have commissioned.",
                "image": "console/images/illustrations/outline/lab_tablet.svg",
                "type": "producer",
                "disabled": True,
            },
            {
                "action": "Dive in",
                "title": "🤝 For Everyone Else",
                "description": "We believe that cannabis analytics is for everyone. For all software integrators, researchers, consumers, and data seekers. Cannlytics has something for you. Get your hands on public datasets and explore our catacombs of data.",
                "image": "console/images/illustrations/outline/lab_desktop.svg",
                "type": "integrator",
                "disabled": True,
            },
        ],
    },
    "sidebar": {},
}
